//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer Uniforms
// {
//
//   float4x4 u_modelViewProj;          // Offset:    0 Size:    64
//   float4x4 u_modelView;              // Offset:   64 Size:    64
//   float4x4 u_model;                  // Offset:  128 Size:    64 [unused]
//   float4x4 u_viewProj;               // Offset:  192 Size:    64 [unused]
//   float4 u_lightParams;              // Offset:  256 Size:    16
//   float4 u_material[5];              // Offset:  272 Size:    80
//   float4 u_fogParams;                // Offset:  352 Size:    16
//   float4 u_lights[56];               // Offset:  368 Size:   896
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// Uniforms                          cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float   xyz 
// NORMAL                   0   xyz         1     NONE   float   xyz 
// COLOR                    0   xyzw        2     NONE   float       
// TEXCOORD                 0   xy          3     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
// COLOR                    0   xyzw        1     NONE   float   xyzw
// COLOR                    1   xyzw        2     NONE   float   xyzw
// TEXCOORD                 0   xy          3     NONE   float   xy  
// TEXCOORD                 1     z         3     NONE   float     z 
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[79], dynamicIndexed
dcl_input v0.xyz
dcl_input v1.xyz
dcl_input v3.xy
dcl_output_siv o0.xyzw, position
dcl_output o1.xyzw
dcl_output o2.xyzw
dcl_output o3.xy
dcl_output o3.z
dcl_temps 10
mul r0.xyzw, v0.yyyy, cb0[1].xyzw
mad r0.xyzw, cb0[0].xyzw, v0.xxxx, r0.xyzw
mad r0.xyzw, cb0[2].xyzw, v0.zzzz, r0.xyzw
add o0.xyzw, r0.xyzw, cb0[3].xyzw
mul r0.xyz, v0.yyyy, cb0[5].xyzx
mad r0.xyz, cb0[4].xyzx, v0.xxxx, r0.xyzx
mad r0.xyz, cb0[6].xyzx, v0.zzzz, r0.xyzx
add r0.xyz, r0.xyzx, cb0[7].xyzx
mul r1.xyz, v1.yyyy, cb0[5].xyzx
mad r1.xyz, cb0[4].xyzx, v1.xxxx, r1.xyzx
mad r1.xyz, cb0[6].xyzx, v1.zzzz, r1.xyzx
dp3 r0.w, r1.xyzx, r1.xyzx
rsq r0.w, r0.w
mul r1.xyz, r0.wwww, r1.xyzx
ftoi r0.w, cb0[16].x
mad r2.xyz, cb0[18].xyzx, cb0[16].yzwy, cb0[20].xyzx
lt r1.w, l(0.000000), cb0[21].x
mov r3.w, l(1.000000)
mov r4.xyz, r2.xyzx
mov r5.xyz, l(0,0,0,0)
mov r2.w, l(0)
loop 
  ige r4.w, r2.w, l(8)
  breakc_nz r4.w
  ige r4.w, r2.w, r0.w
  if_nz r4.w
    break 
  endif 
  imul null, r4.w, r2.w, l(7)
  imad r6.xyzw, r2.wwww, l(7, 7, 7, 7), l(1, 2, 3, 4)
  imad r7.xy, r2.wwww, l(7, 7, 0, 0), l(5, 6, 0, 0)
  lt r5.w, cb0[r4.w + 23].w, l(0.500000)
  add r8.xyz, -r0.xyzx, cb0[r4.w + 23].xyzx
  dp3 r7.z, r8.xyzx, r8.xyzx
  sqrt r7.w, r7.z
  max r8.w, r7.w, l(0.000100)
  div r8.xyz, r8.xyzx, r8.wwww
  mad r9.x, cb0[r7.x + 23].y, r7.w, cb0[r7.x + 23].x
  mad r7.z, r7.z, cb0[r7.x + 23].z, r9.x
  div r7.z, l(1.000000, 1.000000, 1.000000, 1.000000), r7.z
  lt r9.x, l(0.000000), cb0[r6.x + 23].w
  lt r7.w, cb0[r6.x + 23].w, r7.w
  and r7.w, r7.w, r9.x
  movc r7.z, r7.w, l(0), r7.z
  lt r4.w, l(1.500000), cb0[r4.w + 23].w
  dp3 r7.w, cb0[r6.x + 23].xyzx, cb0[r6.x + 23].xyzx
  rsq r7.w, r7.w
  mul r9.xyz, r7.wwww, cb0[r6.x + 23].xyzx
  dp3 r7.w, -r8.xyzx, r9.xyzx
  add r9.x, -cb0[r7.y + 23].y, cb0[r7.y + 23].x
  lt r9.y, |r9.x|, l(0.000100)
  movc r9.x, r9.y, l(0.000100), r9.x
  add r7.y, r7.w, -cb0[r7.y + 23].y
  div_sat r7.y, r7.y, r9.x
  max r7.y, r7.y, l(0.000100)
  log r7.y, r7.y
  mul r7.x, r7.y, cb0[r7.x + 23].w
  exp r7.x, r7.x
  mul r7.x, r7.x, r7.z
  movc r8.w, r4.w, r7.x, r7.z
  mov r3.xyz, -cb0[r6.x + 23].xyzx
  movc r7.xyzw, r5.wwww, r3.xyzw, r8.xyzw
  dp3 r3.x, r7.xyzx, r7.xyzx
  rsq r3.x, r3.x
  mul r8.xyz, r3.xxxx, r7.xyzx
  dp3 r3.y, r1.xyzx, r8.xyzx
  max r3.y, r3.y, l(0.000000)
  mul r8.xyz, cb0[17].xyzx, cb0[r6.y + 23].xyzx
  mul r8.xyz, r3.yyyy, r8.xyzx
  mad r8.xyz, r8.xyzx, r7.wwww, r4.xyzx
  mul r6.xyw, cb0[18].xyxz, cb0[r6.w + 23].xyxz
  mad r4.xyz, r6.xywx, r7.wwww, r8.xyzx
  lt r3.y, l(0.000000), r3.y
  and r3.y, r1.w, r3.y
  mad r6.xyw, r7.xyxz, r3.xxxx, l(0.000000, 0.000000, 0.000000, 1.000000)
  dp3 r3.x, r6.xywx, r6.xywx
  rsq r3.x, r3.x
  mul r6.xyw, r3.xxxx, r6.xyxw
  dp3 r3.x, r1.xyzx, r6.xywx
  max r3.x, r3.x, l(0.000000)
  mul r6.xyz, cb0[19].xyzx, cb0[r6.z + 23].xyzx
  log r3.x, r3.x
  mul r3.x, r3.x, cb0[21].x
  exp r3.x, r3.x
  mul r6.xyz, r3.xxxx, r6.xyzx
  mad r6.xyz, r6.xyzx, r7.wwww, r5.xyzx
  movc r5.xyz, r3.yyyy, r6.xyzx, r5.xyzx
  iadd r2.w, r2.w, l(1)
endloop 
mov_sat o1.xyz, r4.xyzx
mov_sat o2.xyz, r5.xyzx
ge r0.x, cb0[22].w, l(0.500000)
add r0.y, -|r0.z|, cb0[22].y
add r0.w, -cb0[22].x, cb0[22].y
div_sat r0.y, r0.y, r0.w
lt r1.xy, cb0[22].wwww, l(1.500000, 2.500000, 0.000000, 0.000000)
mul r0.z, |r0.z|, cb0[22].z
mul r0.w, r0.z, l(-1.442695)
exp r0.w, r0.w
min r0.w, r0.w, l(1.000000)
mul r0.z, r0.z, r0.z
mul r0.z, r0.z, l(-1.442695)
exp r0.z, r0.z
movc r0.z, r1.y, r0.w, r0.z
movc r0.y, r1.x, r0.y, r0.z
movc o3.z, r0.x, r0.y, l(1.000000)
mov o1.w, cb0[17].w
mov o2.w, l(0)
mov o3.xy, v3.xyxx
ret 
// Approximately 110 instruction slots used
