"""Generate shader-language constants from the C++ fixed-function ABI."""

from __future__ import annotations

from pathlib import Path
import re


SAMPLER_STATE_ENUM = "CKFFSamplerShaderStateABI"


def sampler_shader_state_constants(header: Path) -> list[tuple[str, int]]:
    text = header.read_text(encoding="utf-8")
    match = re.search(
        rf"enum\s+{SAMPLER_STATE_ENUM}\s*\{{(?P<body>.*?)\}};",
        text,
        re.DOTALL,
    )
    if not match:
        raise ValueError(f"{header}: missing {SAMPLER_STATE_ENUM}")

    constants: list[tuple[str, int]] = []
    row = re.compile(
        r"^\s*(CKFF_SAMPLER_SHADER_[A-Z0-9_]+)\s*=\s*"
        r"(0x[0-9a-fA-F]+|[0-9]+)u?\s*,?\s*$"
    )
    for line_number, raw in enumerate(match.group("body").splitlines(), 1):
        line = raw.split("//", 1)[0].strip()
        if not line:
            continue
        entry = row.match(line)
        if not entry:
            raise ValueError(
                f"{header.name}:{line_number}: sampler ABI values must be "
                f"numeric literals: {raw.strip()}"
            )
        constants.append((entry.group(1), int(entry.group(2), 0)))

    if not constants:
        raise ValueError(f"{header}: empty {SAMPLER_STATE_ENUM}")
    return constants


def sampler_shader_state_source(header: Path) -> str:
    lines = [
        "// Auto-generated by shader_abi_codegen.py from CKFFShaderABI.h - DO NOT EDIT",
        "// CKFFSamplerShaderState is transported as one exact 24-bit fp32 integer.",
        "",
    ]
    for name, value in sampler_shader_state_constants(header):
        encoded = str(value) if name.endswith("_SHIFT") else f"0x{value:08x}"
        lines.append(f"#define {name} {encoded}")
    lines.append("")
    return "\n".join(lines)


def sync_sampler_shader_state(header: Path, shader: Path, verify: bool = False) -> None:
    expected = sampler_shader_state_source(header)
    if verify:
        actual = shader.read_text(encoding="utf-8")
        if actual != expected:
            raise ValueError(
                f"{shader}: stale sampler shader ABI; regenerate shader artifacts"
            )
        return
    shader.write_text(expected, encoding="utf-8", newline="\n")
