"""Generate shader-language constants from the C++ fixed-function ABI."""

from __future__ import annotations

from pathlib import Path
import re


SAMPLER_STATE_ENUM = "CKFFSamplerShaderStateABI"


class SamplerLayout:
    def __init__(self, name: str, value: int, two_d: int,
                 cube: int, volume: int) -> None:
        self.name = name
        self.value = value
        self.counts = (two_d, cube, volume)

    @property
    def bases(self) -> tuple[int, int, int]:
        return (0, self.counts[0], self.counts[0] + self.counts[1])


def sampler_layouts(definition: Path) -> list[SamplerLayout]:
    row = re.compile(
        r"^\s*CKFF_SAMPLER_LAYOUT\(\s*([A-Z0-9_]+)\s*,\s*(\d+)\s*,"
        r"\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\)\s*$"
    )
    layouts: list[SamplerLayout] = []
    for line_number, raw in enumerate(
            definition.read_text(encoding="utf-8").splitlines(), 1):
        line = raw.split("//", 1)[0].strip()
        if not line:
            continue
        match = row.match(line)
        if not match:
            raise ValueError(
                f"{definition.name}:{line_number}: invalid sampler layout row"
            )
        name, value, two_d, cube, volume = match.groups()
        layouts.append(SamplerLayout(
            name, int(value), int(two_d), int(cube), int(volume)))

    if [layout.value for layout in layouts] != list(range(len(layouts))):
        raise ValueError(f"{definition}: sampler layout ids must be contiguous")
    for layout in layouts:
        if sum(layout.counts) != 16:
            raise ValueError(
                f"{definition}: {layout.name} must describe sixteen slots")
        if sorted(layout.counts) != [4, 4, 8]:
            raise ValueError(
                f"{definition}: {layout.name} must have one wide sampler block")
    if {layout.name for layout in layouts} != {
            "WIDE_2D", "WIDE_CUBE", "WIDE_VOLUME"}:
        raise ValueError(f"{definition}: incomplete fixed-function layouts")
    return layouts


def _dispatch_macro(name: str, selector: str, result: str, operation: str,
                    sampler_names: list[tuple[int, str]]) -> list[str]:
    if not sampler_names:
        return [f"#define {name}({selector}, {result}, {operation})"]
    lines = [f"#define {name}({selector}, {result}, {operation}) \\"]
    for index, (value, sampler) in enumerate(sampler_names):
        prefix = "if" if index == 0 else "else if"
        final = " \\" if index + 1 < len(sampler_names) else ""
        lines.append(
            f"    {prefix} (({selector}) == {value}) "
            f"{{ ({result}) = {operation}({sampler}); }}{final}"
        )
    return lines


def _select_macro(name: str,
                  sampler_names: list[tuple[int, str]]) -> list[str]:
    # A native selection applies a statement to the texture and sampler of
    # the resource an index selects.
    if not sampler_names:
        return [f"#define {name}(_index, _statement)"]
    lines = [f"#define {name}(_index, _statement) \\",
             "    switch (_index) { \\"]
    for value, sampler in sampler_names:
        lines.append(f"    case {value}: _statement({sampler}, "
                     f"{sampler}Sampler); break; \\")
    lines.append("    }")
    return lines


def _handle_dispatch_macro(name: str, selector: str, handle: str, base: str,
                           sampler_names: list[tuple[int, str]]) -> list[str]:
    # A native dispatch passes the operation a handle of the resource the
    # selector selects among sampler_names, whose ordinals are contiguous.
    if not sampler_names:
        return [f"#define {name}({selector}, _result, _operation)"]
    first, end = sampler_names[0][0], sampler_names[-1][0] + 1
    return [
        f"#define {name}({selector}, _result, _operation) \\",
        f"    CKFF_DISPATCH_HANDLE({handle}, {base}, {first}, {end}, "
        f"{selector}, _result, _operation)",
    ]


def sampler_layout_source(definition: Path) -> str:
    layouts = sampler_layouts(definition)
    lines = [
        "// Auto-generated by shader_abi_codegen.py from CKFFSamplerLayout.def - DO NOT EDIT",
        "// Sampler declarations and every ordinal dispatch share this layout.",
        "",
        "#ifndef CKFF_NATIVE_SAMPLER_LAYOUT",
        "#define CKFF_NATIVE_SAMPLER_LAYOUT 0",
        "#endif",
        "",
    ]
    sampler_prefixes = ("s_texture", "s_textureCube", "s_textureVolume")
    sampler_declarations = ("SAMPLER2D", "SAMPLERCUBE", "SAMPLER3D")

    for layout_index, layout in enumerate(layouts):
        lines.append(("#if" if layout_index == 0 else "#elif") +
                     f" CKFF_NATIVE_SAMPLER_LAYOUT == {layout.value}")
        bases = layout.bases
        lines += [
            f"#define CKFF_2D_SLOT_BASE {bases[0]}",
            f"#define CKFF_CUBE_SLOT_BASE {bases[1]}",
            f"#define CKFF_VOLUME_SLOT_BASE {bases[2]}",
            f"#define CKFF_2D_SLOT_COUNT {layout.counts[0]}",
            f"#define CKFF_CUBE_SLOT_COUNT {layout.counts[1]}",
            f"#define CKFF_VOLUME_SLOT_COUNT {layout.counts[2]}",
        ]
        for type_index, (count, base, prefix, declaration) in enumerate(zip(
                layout.counts, bases, sampler_prefixes, sampler_declarations)):
            array_volume = type_index == 2 and layout.name == "WIDE_VOLUME"
            if array_volume:
                lines += [
                    "#if CKFF_NATIVE_SDL_GPU && !defined(__spirv__)",
                    f"Texture3D<float4> s_textureVolume[{count}] : register(t{base}, space2);",
                    f"SamplerState s_textureVolumeSampler[{count}] : register(s{base}, space2);",
                    "#define CKFF_VOLUME_RESOURCE_ARRAY 1",
                    "#else",
                ]
            for ordinal in range(count):
                lines.append(
                    f"{declaration}({prefix}{ordinal}, {base + ordinal});")
            if array_volume:
                lines += ["#define CKFF_VOLUME_RESOURCE_ARRAY 0", "#endif"]

        two_d = [(ordinal, f"s_texture{ordinal}")
                 for ordinal in range(layout.counts[0])]
        cube = [(ordinal, f"s_textureCube{ordinal}")
                for ordinal in range(layout.counts[1])]
        volume = [(ordinal, f"s_textureVolume{ordinal}")
                  for ordinal in range(layout.counts[2])]

        # Native dispatches pass handles (sampler_handles.hlsli), whose
        # methods select each resource with these selections.
        lines.append("#if CKFF_NATIVE_SDL_GPU")
        lines += _select_macro("CKFF_SELECT_CUBE", cube)
        if layout.name == "WIDE_VOLUME":
            lines += [
                "#if CKFF_VOLUME_RESOURCE_ARRAY",
                "#define CKFF_SELECT_VOLUME(_index, _statement) \\",
                "    { _statement(s_textureVolume[_index], "
                "s_textureVolumeSampler[_index]); }",
                "#else",
            ]
            lines += _select_macro("CKFF_SELECT_VOLUME", volume)
            lines.append("#endif")
        else:
            lines += _select_macro("CKFF_SELECT_VOLUME", volume)
        lines += _handle_dispatch_macro(
            "CKFF_DISPATCH_CUBE", "_ordinal", "CKFFTextureCube",
            "CKFF_CUBE_SLOT_BASE", cube)
        lines += _handle_dispatch_macro(
            "CKFF_DISPATCH_VOLUME", "_ordinal", "CKFFTexture3D",
            "CKFF_VOLUME_SLOT_BASE", volume)
        for compare_count in range(layout.counts[0] + 1):
            lines.append(("#if" if compare_count == 0 else "#elif") +
                         f" CKFF_DEPTH_COMPARE_SAMPLER_COUNT == {compare_count}")
            ordinary = two_d[compare_count:]
            compare = two_d[:compare_count]
            lines += _select_macro("CKFF_SELECT_2D", ordinary)
            lines += _select_macro("CKFF_SELECT_DEPTH_2D", compare)
            if not compare:
                # Only a layout of ordinary 2D resources dispatches them all.
                lines += _handle_dispatch_macro(
                    "CKFF_DISPATCH_2D_ALL", "_ordinal", "CKFFTexture2D",
                    "CKFF_2D_SLOT_BASE", ordinary)
                lines += _handle_dispatch_macro(
                    "CKFF_DISPATCH_2D_STAGE", "_stage", "CKFFTexture2D",
                    "CKFF_2D_SLOT_BASE", ordinary)
            lines += _handle_dispatch_macro(
                "CKFF_DISPATCH_2D_ORDINARY", "_ordinal", "CKFFTexture2D",
                "CKFF_2D_SLOT_BASE", ordinary)
            lines += _handle_dispatch_macro(
                "CKFF_DISPATCH_DEPTH_COMPARE", "_ordinal",
                "CKFFDepthTexture2D", "CKFF_2D_SLOT_BASE", compare)
        lines += ["#endif", "#else"]
        lines += _dispatch_macro(
            "CKFF_DISPATCH_2D_ALL", "_ordinal", "_result", "_operation",
            two_d)
        lines += _dispatch_macro(
            "CKFF_DISPATCH_2D_STAGE", "_stage", "_result", "_operation",
            two_d)
        lines += _dispatch_macro(
            "CKFF_DISPATCH_CUBE", "_ordinal", "_result", "_operation",
            cube)
        lines += _dispatch_macro(
            "CKFF_DISPATCH_VOLUME", "_ordinal", "_result", "_operation",
            volume)
        lines += _dispatch_macro(
            "CKFF_DISPATCH_2D_ORDINARY", "_ordinal", "_result",
            "_operation", two_d)
        lines += _dispatch_macro(
            "CKFF_DISPATCH_DEPTH_COMPARE", "_ordinal", "_result",
            "_operation", [])
        lines.append("#endif")

    lines += [
        "#else",
        "#error Unsupported CKFF_NATIVE_SAMPLER_LAYOUT",
        "#endif",
        "",
    ]
    return "\n".join(lines)


def sync_sampler_layout(definition: Path, shader: Path,
                        verify: bool = False) -> None:
    expected = sampler_layout_source(definition)
    if verify:
        actual = shader.read_text(encoding="utf-8")
        if actual != expected:
            raise ValueError(
                f"{shader}: stale sampler layout; regenerate shader artifacts")
        return
    shader.write_text(expected, encoding="utf-8", newline="\n")


def sampler_shader_state_constants(header: Path) -> list[tuple[str, int]]:
    text = header.read_text(encoding="utf-8")
    match = re.search(
        rf"enum\s+{SAMPLER_STATE_ENUM}\s*\{{(?P<body>.*?)\}};",
        text,
        re.DOTALL,
    )
    if not match:
        raise ValueError(f"{header}: missing {SAMPLER_STATE_ENUM}")

    constants: list[tuple[str, int]] = []
    row = re.compile(
        r"^\s*(CKFF_SAMPLER_SHADER_[A-Z0-9_]+)\s*=\s*"
        r"(0x[0-9a-fA-F]+|[0-9]+)u?\s*,?\s*$"
    )
    for line_number, raw in enumerate(match.group("body").splitlines(), 1):
        line = raw.split("//", 1)[0].strip()
        if not line:
            continue
        entry = row.match(line)
        if not entry:
            raise ValueError(
                f"{header.name}:{line_number}: sampler ABI values must be "
                f"numeric literals: {raw.strip()}"
            )
        constants.append((entry.group(1), int(entry.group(2), 0)))

    if not constants:
        raise ValueError(f"{header}: empty {SAMPLER_STATE_ENUM}")
    return constants


def sampler_shader_state_source(header: Path) -> str:
    lines = [
        "// Auto-generated by shader_abi_codegen.py from CKFFShaderABI.h - DO NOT EDIT",
        "// CKFFSamplerShaderState is transported as one exact 24-bit fp32 integer.",
        "",
    ]
    for name, value in sampler_shader_state_constants(header):
        encoded = str(value) if name.endswith("_SHIFT") else f"0x{value:08x}"
        lines.append(f"#define {name} {encoded}")
    lines.append("")
    return "\n".join(lines)


def sync_sampler_shader_state(header: Path, shader: Path, verify: bool = False) -> None:
    expected = sampler_shader_state_source(header)
    if verify:
        actual = shader.read_text(encoding="utf-8")
        if actual != expected:
            raise ValueError(
                f"{shader}: stale sampler shader ABI; regenerate shader artifacts"
            )
        return
    shader.write_text(expected, encoding="utf-8", newline="\n")
