// Auto-generated by compile_shaders.py gen-fragment-program-layout from CKFFFragmentProgramLayout.def - DO NOT EDIT
// Requires int ckffProgramBits(int lane, int offset, int bits) to be defined before inclusion.

#define CKFF_FRAGMENT_PROGRAM_LANE_BITS 24
#define CKFF_FRAGMENT_PROGRAM_LANE_COUNT 20
#define CKFF_FRAGMENT_PROGRAM_VEC4_COUNT 5
#define CKFF_FRAGMENT_PROGRAM_STAGE_COUNT 8
#define CKFF_FRAGMENT_PROGRAM_STAGE_LANE_BASE 0
#define CKFF_FRAGMENT_PROGRAM_STAGE_LANE_STRIDE 2
#define CKFF_FRAGMENT_PROGRAM_GLOBAL_LANE_BASE 16

int ckffProgramStageBits(int stage, int laneInStage, int offset, int bits)
{
    return ckffProgramBits(CKFF_FRAGMENT_PROGRAM_STAGE_LANE_BASE + stage * CKFF_FRAGMENT_PROGRAM_STAGE_LANE_STRIDE + laneInStage, offset, bits);
}

int ckffProgramStage_COLOR_OP(int stage) { return ckffProgramStageBits(stage, 0, 0, 5); }
int ckffProgramStage_COLOR_ARG1(int stage) { return ckffProgramStageBits(stage, 0, 5, 5); }
int ckffProgramStage_COLOR_ARG2(int stage) { return ckffProgramStageBits(stage, 0, 10, 5); }
int ckffProgramStage_COLOR_ARG0(int stage) { return ckffProgramStageBits(stage, 0, 15, 5); }
int ckffProgramStage_RESULT_IS_TEMP(int stage) { return ckffProgramStageBits(stage, 0, 20, 1); }
int ckffProgramStage_SAMPLER_TYPE(int stage) { return ckffProgramStageBits(stage, 0, 21, 2); }
int ckffProgramStage_PROJECTED(int stage) { return ckffProgramStageBits(stage, 0, 23, 1); }
int ckffProgramStage_ALPHA_OP(int stage) { return ckffProgramStageBits(stage, 1, 0, 5); }
int ckffProgramStage_ALPHA_ARG1(int stage) { return ckffProgramStageBits(stage, 1, 5, 5); }
int ckffProgramStage_ALPHA_ARG2(int stage) { return ckffProgramStageBits(stage, 1, 10, 5); }
int ckffProgramStage_ALPHA_ARG0(int stage) { return ckffProgramStageBits(stage, 1, 15, 5); }
int ckffProgramStage_SAMPLER_COMPARE_FUNC(int stage) { return ckffProgramStageBits(stage, 1, 20, 4); }

int ckffProgram_LAST_ACTIVE_TEXTURE_STAGE() { return ckffProgramBits(16, 0, 3); }
int ckffProgram_ALPHA_TEST_ENABLED() { return ckffProgramBits(16, 3, 1); }
int ckffProgram_ALPHA_FUNC() { return ckffProgramBits(16, 4, 4); }
int ckffProgram_FOG_ENABLED() { return ckffProgramBits(16, 8, 1); }
int ckffProgram_VERTEX_FOG_MODE() { return ckffProgramBits(16, 9, 2); }
int ckffProgram_PIXEL_FOG_MODE() { return ckffProgramBits(16, 11, 2); }
int ckffProgram_RANGE_FOG() { return ckffProgramBits(16, 13, 1); }
int ckffProgram_FLAT_SHADE() { return ckffProgramBits(16, 14, 1); }
int ckffProgram_GLOBAL_SPECULAR_ENABLED() { return ckffProgramBits(16, 15, 1); }
int ckffProgram_SAMPLER_ORDINALS() { return ckffProgramBits(17, 0, 24); }
