// Auto-generated by shader_abi_codegen.py from CKFFSamplerLayout.def - DO NOT EDIT
// Sampler declarations and every ordinal dispatch share this layout.

#ifndef CKFF_NATIVE_SAMPLER_LAYOUT
#define CKFF_NATIVE_SAMPLER_LAYOUT 0
#endif

#if CKFF_NATIVE_SAMPLER_LAYOUT == 0
#define CKFF_2D_SLOT_BASE 0
#define CKFF_CUBE_SLOT_BASE 8
#define CKFF_VOLUME_SLOT_BASE 12
#define CKFF_2D_SLOT_COUNT 8
#define CKFF_CUBE_SLOT_COUNT 4
#define CKFF_VOLUME_SLOT_COUNT 4
SAMPLER2D(s_texture0, 0);
SAMPLER2D(s_texture1, 1);
SAMPLER2D(s_texture2, 2);
SAMPLER2D(s_texture3, 3);
SAMPLER2D(s_texture4, 4);
SAMPLER2D(s_texture5, 5);
SAMPLER2D(s_texture6, 6);
SAMPLER2D(s_texture7, 7);
SAMPLERCUBE(s_textureCube0, 8);
SAMPLERCUBE(s_textureCube1, 9);
SAMPLERCUBE(s_textureCube2, 10);
SAMPLERCUBE(s_textureCube3, 11);
SAMPLER3D(s_textureVolume0, 12);
SAMPLER3D(s_textureVolume1, 13);
SAMPLER3D(s_textureVolume2, 14);
SAMPLER3D(s_textureVolume3, 15);
#define CKFF_DISPATCH_2D_ALL(_ordinal, _result, _operation) \
    if ((_ordinal) == 0) { (_result) = _operation(s_texture0); } \
    else if ((_ordinal) == 1) { (_result) = _operation(s_texture1); } \
    else if ((_ordinal) == 2) { (_result) = _operation(s_texture2); } \
    else if ((_ordinal) == 3) { (_result) = _operation(s_texture3); } \
    else if ((_ordinal) == 4) { (_result) = _operation(s_texture4); } \
    else if ((_ordinal) == 5) { (_result) = _operation(s_texture5); } \
    else if ((_ordinal) == 6) { (_result) = _operation(s_texture6); } \
    else if ((_ordinal) == 7) { (_result) = _operation(s_texture7); }
#define CKFF_DISPATCH_2D_STAGE(_stage, _result, _operation) \
    if ((_stage) == 0) { (_result) = _operation(s_texture0); } \
    else if ((_stage) == 1) { (_result) = _operation(s_texture1); } \
    else if ((_stage) == 2) { (_result) = _operation(s_texture2); } \
    else if ((_stage) == 3) { (_result) = _operation(s_texture3); } \
    else if ((_stage) == 4) { (_result) = _operation(s_texture4); } \
    else if ((_stage) == 5) { (_result) = _operation(s_texture5); } \
    else if ((_stage) == 6) { (_result) = _operation(s_texture6); } \
    else if ((_stage) == 7) { (_result) = _operation(s_texture7); }
#define CKFF_DISPATCH_CUBE(_ordinal, _result, _operation) \
    if ((_ordinal) == 0) { (_result) = _operation(s_textureCube0); } \
    else if ((_ordinal) == 1) { (_result) = _operation(s_textureCube1); } \
    else if ((_ordinal) == 2) { (_result) = _operation(s_textureCube2); } \
    else if ((_ordinal) == 3) { (_result) = _operation(s_textureCube3); }
#define CKFF_DISPATCH_VOLUME(_ordinal, _result, _operation) \
    if ((_ordinal) == 0) { (_result) = _operation(s_textureVolume0); } \
    else if ((_ordinal) == 1) { (_result) = _operation(s_textureVolume1); } \
    else if ((_ordinal) == 2) { (_result) = _operation(s_textureVolume2); } \
    else if ((_ordinal) == 3) { (_result) = _operation(s_textureVolume3); }
#if CKFF_NATIVE_SDL_GPU
#if CKFF_DEPTH_COMPARE_SAMPLER_COUNT == 0
#define CKFF_DISPATCH_2D_ORDINARY(_ordinal, _result, _operation) \
    if ((_ordinal) == 0) { (_result) = _operation(s_texture0); } \
    else if ((_ordinal) == 1) { (_result) = _operation(s_texture1); } \
    else if ((_ordinal) == 2) { (_result) = _operation(s_texture2); } \
    else if ((_ordinal) == 3) { (_result) = _operation(s_texture3); } \
    else if ((_ordinal) == 4) { (_result) = _operation(s_texture4); } \
    else if ((_ordinal) == 5) { (_result) = _operation(s_texture5); } \
    else if ((_ordinal) == 6) { (_result) = _operation(s_texture6); } \
    else if ((_ordinal) == 7) { (_result) = _operation(s_texture7); }
#define CKFF_DISPATCH_DEPTH_COMPARE(_ordinal, _result, _operation)
#elif CKFF_DEPTH_COMPARE_SAMPLER_COUNT == 1
#define CKFF_DISPATCH_2D_ORDINARY(_ordinal, _result, _operation) \
    if ((_ordinal) == 1) { (_result) = _operation(s_texture1); } \
    else if ((_ordinal) == 2) { (_result) = _operation(s_texture2); } \
    else if ((_ordinal) == 3) { (_result) = _operation(s_texture3); } \
    else if ((_ordinal) == 4) { (_result) = _operation(s_texture4); } \
    else if ((_ordinal) == 5) { (_result) = _operation(s_texture5); } \
    else if ((_ordinal) == 6) { (_result) = _operation(s_texture6); } \
    else if ((_ordinal) == 7) { (_result) = _operation(s_texture7); }
#define CKFF_DISPATCH_DEPTH_COMPARE(_ordinal, _result, _operation) \
    if ((_ordinal) == 0) { (_result) = _operation(s_texture0); }
#elif CKFF_DEPTH_COMPARE_SAMPLER_COUNT == 2
#define CKFF_DISPATCH_2D_ORDINARY(_ordinal, _result, _operation) \
    if ((_ordinal) == 2) { (_result) = _operation(s_texture2); } \
    else if ((_ordinal) == 3) { (_result) = _operation(s_texture3); } \
    else if ((_ordinal) == 4) { (_result) = _operation(s_texture4); } \
    else if ((_ordinal) == 5) { (_result) = _operation(s_texture5); } \
    else if ((_ordinal) == 6) { (_result) = _operation(s_texture6); } \
    else if ((_ordinal) == 7) { (_result) = _operation(s_texture7); }
#define CKFF_DISPATCH_DEPTH_COMPARE(_ordinal, _result, _operation) \
    if ((_ordinal) == 0) { (_result) = _operation(s_texture0); } \
    else if ((_ordinal) == 1) { (_result) = _operation(s_texture1); }
#elif CKFF_DEPTH_COMPARE_SAMPLER_COUNT == 3
#define CKFF_DISPATCH_2D_ORDINARY(_ordinal, _result, _operation) \
    if ((_ordinal) == 3) { (_result) = _operation(s_texture3); } \
    else if ((_ordinal) == 4) { (_result) = _operation(s_texture4); } \
    else if ((_ordinal) == 5) { (_result) = _operation(s_texture5); } \
    else if ((_ordinal) == 6) { (_result) = _operation(s_texture6); } \
    else if ((_ordinal) == 7) { (_result) = _operation(s_texture7); }
#define CKFF_DISPATCH_DEPTH_COMPARE(_ordinal, _result, _operation) \
    if ((_ordinal) == 0) { (_result) = _operation(s_texture0); } \
    else if ((_ordinal) == 1) { (_result) = _operation(s_texture1); } \
    else if ((_ordinal) == 2) { (_result) = _operation(s_texture2); }
#elif CKFF_DEPTH_COMPARE_SAMPLER_COUNT == 4
#define CKFF_DISPATCH_2D_ORDINARY(_ordinal, _result, _operation) \
    if ((_ordinal) == 4) { (_result) = _operation(s_texture4); } \
    else if ((_ordinal) == 5) { (_result) = _operation(s_texture5); } \
    else if ((_ordinal) == 6) { (_result) = _operation(s_texture6); } \
    else if ((_ordinal) == 7) { (_result) = _operation(s_texture7); }
#define CKFF_DISPATCH_DEPTH_COMPARE(_ordinal, _result, _operation) \
    if ((_ordinal) == 0) { (_result) = _operation(s_texture0); } \
    else if ((_ordinal) == 1) { (_result) = _operation(s_texture1); } \
    else if ((_ordinal) == 2) { (_result) = _operation(s_texture2); } \
    else if ((_ordinal) == 3) { (_result) = _operation(s_texture3); }
#elif CKFF_DEPTH_COMPARE_SAMPLER_COUNT == 5
#define CKFF_DISPATCH_2D_ORDINARY(_ordinal, _result, _operation) \
    if ((_ordinal) == 5) { (_result) = _operation(s_texture5); } \
    else if ((_ordinal) == 6) { (_result) = _operation(s_texture6); } \
    else if ((_ordinal) == 7) { (_result) = _operation(s_texture7); }
#define CKFF_DISPATCH_DEPTH_COMPARE(_ordinal, _result, _operation) \
    if ((_ordinal) == 0) { (_result) = _operation(s_texture0); } \
    else if ((_ordinal) == 1) { (_result) = _operation(s_texture1); } \
    else if ((_ordinal) == 2) { (_result) = _operation(s_texture2); } \
    else if ((_ordinal) == 3) { (_result) = _operation(s_texture3); } \
    else if ((_ordinal) == 4) { (_result) = _operation(s_texture4); }
#elif CKFF_DEPTH_COMPARE_SAMPLER_COUNT == 6
#define CKFF_DISPATCH_2D_ORDINARY(_ordinal, _result, _operation) \
    if ((_ordinal) == 6) { (_result) = _operation(s_texture6); } \
    else if ((_ordinal) == 7) { (_result) = _operation(s_texture7); }
#define CKFF_DISPATCH_DEPTH_COMPARE(_ordinal, _result, _operation) \
    if ((_ordinal) == 0) { (_result) = _operation(s_texture0); } \
    else if ((_ordinal) == 1) { (_result) = _operation(s_texture1); } \
    else if ((_ordinal) == 2) { (_result) = _operation(s_texture2); } \
    else if ((_ordinal) == 3) { (_result) = _operation(s_texture3); } \
    else if ((_ordinal) == 4) { (_result) = _operation(s_texture4); } \
    else if ((_ordinal) == 5) { (_result) = _operation(s_texture5); }
#elif CKFF_DEPTH_COMPARE_SAMPLER_COUNT == 7
#define CKFF_DISPATCH_2D_ORDINARY(_ordinal, _result, _operation) \
    if ((_ordinal) == 7) { (_result) = _operation(s_texture7); }
#define CKFF_DISPATCH_DEPTH_COMPARE(_ordinal, _result, _operation) \
    if ((_ordinal) == 0) { (_result) = _operation(s_texture0); } \
    else if ((_ordinal) == 1) { (_result) = _operation(s_texture1); } \
    else if ((_ordinal) == 2) { (_result) = _operation(s_texture2); } \
    else if ((_ordinal) == 3) { (_result) = _operation(s_texture3); } \
    else if ((_ordinal) == 4) { (_result) = _operation(s_texture4); } \
    else if ((_ordinal) == 5) { (_result) = _operation(s_texture5); } \
    else if ((_ordinal) == 6) { (_result) = _operation(s_texture6); }
#elif CKFF_DEPTH_COMPARE_SAMPLER_COUNT == 8
#define CKFF_DISPATCH_2D_ORDINARY(_ordinal, _result, _operation)
#define CKFF_DISPATCH_DEPTH_COMPARE(_ordinal, _result, _operation) \
    if ((_ordinal) == 0) { (_result) = _operation(s_texture0); } \
    else if ((_ordinal) == 1) { (_result) = _operation(s_texture1); } \
    else if ((_ordinal) == 2) { (_result) = _operation(s_texture2); } \
    else if ((_ordinal) == 3) { (_result) = _operation(s_texture3); } \
    else if ((_ordinal) == 4) { (_result) = _operation(s_texture4); } \
    else if ((_ordinal) == 5) { (_result) = _operation(s_texture5); } \
    else if ((_ordinal) == 6) { (_result) = _operation(s_texture6); } \
    else if ((_ordinal) == 7) { (_result) = _operation(s_texture7); }
#endif
#else
#define CKFF_DISPATCH_2D_ORDINARY(_ordinal, _result, _operation) \
    if ((_ordinal) == 0) { (_result) = _operation(s_texture0); } \
    else if ((_ordinal) == 1) { (_result) = _operation(s_texture1); } \
    else if ((_ordinal) == 2) { (_result) = _operation(s_texture2); } \
    else if ((_ordinal) == 3) { (_result) = _operation(s_texture3); } \
    else if ((_ordinal) == 4) { (_result) = _operation(s_texture4); } \
    else if ((_ordinal) == 5) { (_result) = _operation(s_texture5); } \
    else if ((_ordinal) == 6) { (_result) = _operation(s_texture6); } \
    else if ((_ordinal) == 7) { (_result) = _operation(s_texture7); }
#define CKFF_DISPATCH_DEPTH_COMPARE(_ordinal, _result, _operation)
#endif
#elif CKFF_NATIVE_SAMPLER_LAYOUT == 1
#define CKFF_2D_SLOT_BASE 0
#define CKFF_CUBE_SLOT_BASE 4
#define CKFF_VOLUME_SLOT_BASE 12
#define CKFF_2D_SLOT_COUNT 4
#define CKFF_CUBE_SLOT_COUNT 8
#define CKFF_VOLUME_SLOT_COUNT 4
SAMPLER2D(s_texture0, 0);
SAMPLER2D(s_texture1, 1);
SAMPLER2D(s_texture2, 2);
SAMPLER2D(s_texture3, 3);
SAMPLERCUBE(s_textureCube0, 4);
SAMPLERCUBE(s_textureCube1, 5);
SAMPLERCUBE(s_textureCube2, 6);
SAMPLERCUBE(s_textureCube3, 7);
SAMPLERCUBE(s_textureCube4, 8);
SAMPLERCUBE(s_textureCube5, 9);
SAMPLERCUBE(s_textureCube6, 10);
SAMPLERCUBE(s_textureCube7, 11);
SAMPLER3D(s_textureVolume0, 12);
SAMPLER3D(s_textureVolume1, 13);
SAMPLER3D(s_textureVolume2, 14);
SAMPLER3D(s_textureVolume3, 15);
#define CKFF_DISPATCH_2D_ALL(_ordinal, _result, _operation) \
    if ((_ordinal) == 0) { (_result) = _operation(s_texture0); } \
    else if ((_ordinal) == 1) { (_result) = _operation(s_texture1); } \
    else if ((_ordinal) == 2) { (_result) = _operation(s_texture2); } \
    else if ((_ordinal) == 3) { (_result) = _operation(s_texture3); }
#define CKFF_DISPATCH_2D_STAGE(_stage, _result, _operation) \
    if ((_stage) == 0) { (_result) = _operation(s_texture0); } \
    else if ((_stage) == 1) { (_result) = _operation(s_texture1); } \
    else if ((_stage) == 2) { (_result) = _operation(s_texture2); } \
    else if ((_stage) == 3) { (_result) = _operation(s_texture3); }
#define CKFF_DISPATCH_CUBE(_ordinal, _result, _operation) \
    if ((_ordinal) == 0) { (_result) = _operation(s_textureCube0); } \
    else if ((_ordinal) == 1) { (_result) = _operation(s_textureCube1); } \
    else if ((_ordinal) == 2) { (_result) = _operation(s_textureCube2); } \
    else if ((_ordinal) == 3) { (_result) = _operation(s_textureCube3); } \
    else if ((_ordinal) == 4) { (_result) = _operation(s_textureCube4); } \
    else if ((_ordinal) == 5) { (_result) = _operation(s_textureCube5); } \
    else if ((_ordinal) == 6) { (_result) = _operation(s_textureCube6); } \
    else if ((_ordinal) == 7) { (_result) = _operation(s_textureCube7); }
#define CKFF_DISPATCH_VOLUME(_ordinal, _result, _operation) \
    if ((_ordinal) == 0) { (_result) = _operation(s_textureVolume0); } \
    else if ((_ordinal) == 1) { (_result) = _operation(s_textureVolume1); } \
    else if ((_ordinal) == 2) { (_result) = _operation(s_textureVolume2); } \
    else if ((_ordinal) == 3) { (_result) = _operation(s_textureVolume3); }
#if CKFF_NATIVE_SDL_GPU
#if CKFF_DEPTH_COMPARE_SAMPLER_COUNT == 0
#define CKFF_DISPATCH_2D_ORDINARY(_ordinal, _result, _operation) \
    if ((_ordinal) == 0) { (_result) = _operation(s_texture0); } \
    else if ((_ordinal) == 1) { (_result) = _operation(s_texture1); } \
    else if ((_ordinal) == 2) { (_result) = _operation(s_texture2); } \
    else if ((_ordinal) == 3) { (_result) = _operation(s_texture3); }
#define CKFF_DISPATCH_DEPTH_COMPARE(_ordinal, _result, _operation)
#elif CKFF_DEPTH_COMPARE_SAMPLER_COUNT == 1
#define CKFF_DISPATCH_2D_ORDINARY(_ordinal, _result, _operation) \
    if ((_ordinal) == 1) { (_result) = _operation(s_texture1); } \
    else if ((_ordinal) == 2) { (_result) = _operation(s_texture2); } \
    else if ((_ordinal) == 3) { (_result) = _operation(s_texture3); }
#define CKFF_DISPATCH_DEPTH_COMPARE(_ordinal, _result, _operation) \
    if ((_ordinal) == 0) { (_result) = _operation(s_texture0); }
#elif CKFF_DEPTH_COMPARE_SAMPLER_COUNT == 2
#define CKFF_DISPATCH_2D_ORDINARY(_ordinal, _result, _operation) \
    if ((_ordinal) == 2) { (_result) = _operation(s_texture2); } \
    else if ((_ordinal) == 3) { (_result) = _operation(s_texture3); }
#define CKFF_DISPATCH_DEPTH_COMPARE(_ordinal, _result, _operation) \
    if ((_ordinal) == 0) { (_result) = _operation(s_texture0); } \
    else if ((_ordinal) == 1) { (_result) = _operation(s_texture1); }
#elif CKFF_DEPTH_COMPARE_SAMPLER_COUNT == 3
#define CKFF_DISPATCH_2D_ORDINARY(_ordinal, _result, _operation) \
    if ((_ordinal) == 3) { (_result) = _operation(s_texture3); }
#define CKFF_DISPATCH_DEPTH_COMPARE(_ordinal, _result, _operation) \
    if ((_ordinal) == 0) { (_result) = _operation(s_texture0); } \
    else if ((_ordinal) == 1) { (_result) = _operation(s_texture1); } \
    else if ((_ordinal) == 2) { (_result) = _operation(s_texture2); }
#elif CKFF_DEPTH_COMPARE_SAMPLER_COUNT == 4
#define CKFF_DISPATCH_2D_ORDINARY(_ordinal, _result, _operation)
#define CKFF_DISPATCH_DEPTH_COMPARE(_ordinal, _result, _operation) \
    if ((_ordinal) == 0) { (_result) = _operation(s_texture0); } \
    else if ((_ordinal) == 1) { (_result) = _operation(s_texture1); } \
    else if ((_ordinal) == 2) { (_result) = _operation(s_texture2); } \
    else if ((_ordinal) == 3) { (_result) = _operation(s_texture3); }
#endif
#else
#define CKFF_DISPATCH_2D_ORDINARY(_ordinal, _result, _operation) \
    if ((_ordinal) == 0) { (_result) = _operation(s_texture0); } \
    else if ((_ordinal) == 1) { (_result) = _operation(s_texture1); } \
    else if ((_ordinal) == 2) { (_result) = _operation(s_texture2); } \
    else if ((_ordinal) == 3) { (_result) = _operation(s_texture3); }
#define CKFF_DISPATCH_DEPTH_COMPARE(_ordinal, _result, _operation)
#endif
#elif CKFF_NATIVE_SAMPLER_LAYOUT == 2
#define CKFF_2D_SLOT_BASE 0
#define CKFF_CUBE_SLOT_BASE 4
#define CKFF_VOLUME_SLOT_BASE 8
#define CKFF_2D_SLOT_COUNT 4
#define CKFF_CUBE_SLOT_COUNT 4
#define CKFF_VOLUME_SLOT_COUNT 8
SAMPLER2D(s_texture0, 0);
SAMPLER2D(s_texture1, 1);
SAMPLER2D(s_texture2, 2);
SAMPLER2D(s_texture3, 3);
SAMPLERCUBE(s_textureCube0, 4);
SAMPLERCUBE(s_textureCube1, 5);
SAMPLERCUBE(s_textureCube2, 6);
SAMPLERCUBE(s_textureCube3, 7);
#if CKFF_NATIVE_SDL_GPU && !defined(__spirv__)
Texture3D<float4> s_textureVolume[8] : register(t8, space2);
SamplerState s_textureVolumeSampler[8] : register(s8, space2);
#define CKFF_VOLUME_RESOURCE_ARRAY 1
#else
SAMPLER3D(s_textureVolume0, 8);
SAMPLER3D(s_textureVolume1, 9);
SAMPLER3D(s_textureVolume2, 10);
SAMPLER3D(s_textureVolume3, 11);
SAMPLER3D(s_textureVolume4, 12);
SAMPLER3D(s_textureVolume5, 13);
SAMPLER3D(s_textureVolume6, 14);
SAMPLER3D(s_textureVolume7, 15);
#define CKFF_VOLUME_RESOURCE_ARRAY 0
#endif
#define CKFF_DISPATCH_2D_ALL(_ordinal, _result, _operation) \
    if ((_ordinal) == 0) { (_result) = _operation(s_texture0); } \
    else if ((_ordinal) == 1) { (_result) = _operation(s_texture1); } \
    else if ((_ordinal) == 2) { (_result) = _operation(s_texture2); } \
    else if ((_ordinal) == 3) { (_result) = _operation(s_texture3); }
#define CKFF_DISPATCH_2D_STAGE(_stage, _result, _operation) \
    if ((_stage) == 0) { (_result) = _operation(s_texture0); } \
    else if ((_stage) == 1) { (_result) = _operation(s_texture1); } \
    else if ((_stage) == 2) { (_result) = _operation(s_texture2); } \
    else if ((_stage) == 3) { (_result) = _operation(s_texture3); }
#define CKFF_DISPATCH_CUBE(_ordinal, _result, _operation) \
    if ((_ordinal) == 0) { (_result) = _operation(s_textureCube0); } \
    else if ((_ordinal) == 1) { (_result) = _operation(s_textureCube1); } \
    else if ((_ordinal) == 2) { (_result) = _operation(s_textureCube2); } \
    else if ((_ordinal) == 3) { (_result) = _operation(s_textureCube3); }
#if !CKFF_NATIVE_SDL_GPU || defined(__spirv__)
#define CKFF_DISPATCH_VOLUME(_ordinal, _result, _operation) \
    if ((_ordinal) == 0) { (_result) = _operation(s_textureVolume0); } \
    else if ((_ordinal) == 1) { (_result) = _operation(s_textureVolume1); } \
    else if ((_ordinal) == 2) { (_result) = _operation(s_textureVolume2); } \
    else if ((_ordinal) == 3) { (_result) = _operation(s_textureVolume3); } \
    else if ((_ordinal) == 4) { (_result) = _operation(s_textureVolume4); } \
    else if ((_ordinal) == 5) { (_result) = _operation(s_textureVolume5); } \
    else if ((_ordinal) == 6) { (_result) = _operation(s_textureVolume6); } \
    else if ((_ordinal) == 7) { (_result) = _operation(s_textureVolume7); }
#endif
#if CKFF_NATIVE_SDL_GPU
#if CKFF_DEPTH_COMPARE_SAMPLER_COUNT == 0
#define CKFF_DISPATCH_2D_ORDINARY(_ordinal, _result, _operation) \
    if ((_ordinal) == 0) { (_result) = _operation(s_texture0); } \
    else if ((_ordinal) == 1) { (_result) = _operation(s_texture1); } \
    else if ((_ordinal) == 2) { (_result) = _operation(s_texture2); } \
    else if ((_ordinal) == 3) { (_result) = _operation(s_texture3); }
#define CKFF_DISPATCH_DEPTH_COMPARE(_ordinal, _result, _operation)
#elif CKFF_DEPTH_COMPARE_SAMPLER_COUNT == 1
#define CKFF_DISPATCH_2D_ORDINARY(_ordinal, _result, _operation) \
    if ((_ordinal) == 1) { (_result) = _operation(s_texture1); } \
    else if ((_ordinal) == 2) { (_result) = _operation(s_texture2); } \
    else if ((_ordinal) == 3) { (_result) = _operation(s_texture3); }
#define CKFF_DISPATCH_DEPTH_COMPARE(_ordinal, _result, _operation) \
    if ((_ordinal) == 0) { (_result) = _operation(s_texture0); }
#elif CKFF_DEPTH_COMPARE_SAMPLER_COUNT == 2
#define CKFF_DISPATCH_2D_ORDINARY(_ordinal, _result, _operation) \
    if ((_ordinal) == 2) { (_result) = _operation(s_texture2); } \
    else if ((_ordinal) == 3) { (_result) = _operation(s_texture3); }
#define CKFF_DISPATCH_DEPTH_COMPARE(_ordinal, _result, _operation) \
    if ((_ordinal) == 0) { (_result) = _operation(s_texture0); } \
    else if ((_ordinal) == 1) { (_result) = _operation(s_texture1); }
#elif CKFF_DEPTH_COMPARE_SAMPLER_COUNT == 3
#define CKFF_DISPATCH_2D_ORDINARY(_ordinal, _result, _operation) \
    if ((_ordinal) == 3) { (_result) = _operation(s_texture3); }
#define CKFF_DISPATCH_DEPTH_COMPARE(_ordinal, _result, _operation) \
    if ((_ordinal) == 0) { (_result) = _operation(s_texture0); } \
    else if ((_ordinal) == 1) { (_result) = _operation(s_texture1); } \
    else if ((_ordinal) == 2) { (_result) = _operation(s_texture2); }
#elif CKFF_DEPTH_COMPARE_SAMPLER_COUNT == 4
#define CKFF_DISPATCH_2D_ORDINARY(_ordinal, _result, _operation)
#define CKFF_DISPATCH_DEPTH_COMPARE(_ordinal, _result, _operation) \
    if ((_ordinal) == 0) { (_result) = _operation(s_texture0); } \
    else if ((_ordinal) == 1) { (_result) = _operation(s_texture1); } \
    else if ((_ordinal) == 2) { (_result) = _operation(s_texture2); } \
    else if ((_ordinal) == 3) { (_result) = _operation(s_texture3); }
#endif
#else
#define CKFF_DISPATCH_2D_ORDINARY(_ordinal, _result, _operation) \
    if ((_ordinal) == 0) { (_result) = _operation(s_texture0); } \
    else if ((_ordinal) == 1) { (_result) = _operation(s_texture1); } \
    else if ((_ordinal) == 2) { (_result) = _operation(s_texture2); } \
    else if ((_ordinal) == 3) { (_result) = _operation(s_texture3); }
#define CKFF_DISPATCH_DEPTH_COMPARE(_ordinal, _result, _operation)
#endif
#else
#error Unsupported CKFF_NATIVE_SAMPLER_LAYOUT
#endif
