// Auto-generated by shader_abi_codegen.py from CKFFSamplerLayout.def - DO NOT EDIT
// Sampler declarations and every ordinal dispatch share this layout.

#ifndef CKFF_NATIVE_SAMPLER_LAYOUT
#define CKFF_NATIVE_SAMPLER_LAYOUT 0
#endif

#if CKFF_NATIVE_SAMPLER_LAYOUT == 0
#define CKFF_2D_SLOT_BASE 0
#define CKFF_CUBE_SLOT_BASE 8
#define CKFF_VOLUME_SLOT_BASE 12
#define CKFF_2D_SLOT_COUNT 8
#define CKFF_CUBE_SLOT_COUNT 4
#define CKFF_VOLUME_SLOT_COUNT 4
SAMPLER2D(s_texture0, 0);
SAMPLER2D(s_texture1, 1);
SAMPLER2D(s_texture2, 2);
SAMPLER2D(s_texture3, 3);
SAMPLER2D(s_texture4, 4);
SAMPLER2D(s_texture5, 5);
SAMPLER2D(s_texture6, 6);
SAMPLER2D(s_texture7, 7);
SAMPLERCUBE(s_textureCube0, 8);
SAMPLERCUBE(s_textureCube1, 9);
SAMPLERCUBE(s_textureCube2, 10);
SAMPLERCUBE(s_textureCube3, 11);
SAMPLER3D(s_textureVolume0, 12);
SAMPLER3D(s_textureVolume1, 13);
SAMPLER3D(s_textureVolume2, 14);
SAMPLER3D(s_textureVolume3, 15);
#define CKFF_SELECT_CUBE(_index, _statement) \
    switch (_index) { \
    case 0: _statement(s_textureCube0, s_textureCube0Sampler); break; \
    case 1: _statement(s_textureCube1, s_textureCube1Sampler); break; \
    case 2: _statement(s_textureCube2, s_textureCube2Sampler); break; \
    case 3: _statement(s_textureCube3, s_textureCube3Sampler); break; \
    }
#define CKFF_SELECT_VOLUME(_index, _statement) \
    switch (_index) { \
    case 0: _statement(s_textureVolume0, s_textureVolume0Sampler); break; \
    case 1: _statement(s_textureVolume1, s_textureVolume1Sampler); break; \
    case 2: _statement(s_textureVolume2, s_textureVolume2Sampler); break; \
    case 3: _statement(s_textureVolume3, s_textureVolume3Sampler); break; \
    }
#define CKFF_DISPATCH_CUBE(_ordinal, _result, _operation) \
    CKFF_DISPATCH_HANDLE(CKFFTextureCube, CKFF_CUBE_SLOT_BASE, 0, 4, _ordinal, _result, _operation)
#define CKFF_DISPATCH_VOLUME(_ordinal, _result, _operation) \
    CKFF_DISPATCH_HANDLE(CKFFTexture3D, CKFF_VOLUME_SLOT_BASE, 0, 4, _ordinal, _result, _operation)
#if CKFF_DEPTH_COMPARE_SAMPLER_COUNT == 0
#define CKFF_SELECT_2D(_index, _statement) \
    switch (_index) { \
    case 0: _statement(s_texture0, s_texture0Sampler); break; \
    case 1: _statement(s_texture1, s_texture1Sampler); break; \
    case 2: _statement(s_texture2, s_texture2Sampler); break; \
    case 3: _statement(s_texture3, s_texture3Sampler); break; \
    case 4: _statement(s_texture4, s_texture4Sampler); break; \
    case 5: _statement(s_texture5, s_texture5Sampler); break; \
    case 6: _statement(s_texture6, s_texture6Sampler); break; \
    case 7: _statement(s_texture7, s_texture7Sampler); break; \
    }
#define CKFF_SELECT_DEPTH_2D(_index, _statement)
#define CKFF_DISPATCH_2D_ALL(_ordinal, _result, _operation) \
    CKFF_DISPATCH_HANDLE(CKFFTexture2D, CKFF_2D_SLOT_BASE, 0, 8, _ordinal, _result, _operation)
#define CKFF_DISPATCH_2D_STAGE(_stage, _result, _operation) \
    CKFF_DISPATCH_HANDLE(CKFFTexture2D, CKFF_2D_SLOT_BASE, 0, 8, _stage, _result, _operation)
#define CKFF_DISPATCH_2D_ORDINARY(_ordinal, _result, _operation) \
    CKFF_DISPATCH_HANDLE(CKFFTexture2D, CKFF_2D_SLOT_BASE, 0, 8, _ordinal, _result, _operation)
#define CKFF_DISPATCH_DEPTH_COMPARE(_ordinal, _result, _operation)
#elif CKFF_DEPTH_COMPARE_SAMPLER_COUNT == 1
#define CKFF_SELECT_2D(_index, _statement) \
    switch (_index) { \
    case 1: _statement(s_texture1, s_texture1Sampler); break; \
    case 2: _statement(s_texture2, s_texture2Sampler); break; \
    case 3: _statement(s_texture3, s_texture3Sampler); break; \
    case 4: _statement(s_texture4, s_texture4Sampler); break; \
    case 5: _statement(s_texture5, s_texture5Sampler); break; \
    case 6: _statement(s_texture6, s_texture6Sampler); break; \
    case 7: _statement(s_texture7, s_texture7Sampler); break; \
    }
#define CKFF_SELECT_DEPTH_2D(_index, _statement) \
    switch (_index) { \
    case 0: _statement(s_texture0, s_texture0Sampler); break; \
    }
#define CKFF_DISPATCH_2D_ORDINARY(_ordinal, _result, _operation) \
    CKFF_DISPATCH_HANDLE(CKFFTexture2D, CKFF_2D_SLOT_BASE, 1, 8, _ordinal, _result, _operation)
#define CKFF_DISPATCH_DEPTH_COMPARE(_ordinal, _result, _operation) \
    CKFF_DISPATCH_HANDLE(CKFFDepthTexture2D, CKFF_2D_SLOT_BASE, 0, 1, _ordinal, _result, _operation)
#elif CKFF_DEPTH_COMPARE_SAMPLER_COUNT == 2
#define CKFF_SELECT_2D(_index, _statement) \
    switch (_index) { \
    case 2: _statement(s_texture2, s_texture2Sampler); break; \
    case 3: _statement(s_texture3, s_texture3Sampler); break; \
    case 4: _statement(s_texture4, s_texture4Sampler); break; \
    case 5: _statement(s_texture5, s_texture5Sampler); break; \
    case 6: _statement(s_texture6, s_texture6Sampler); break; \
    case 7: _statement(s_texture7, s_texture7Sampler); break; \
    }
#define CKFF_SELECT_DEPTH_2D(_index, _statement) \
    switch (_index) { \
    case 0: _statement(s_texture0, s_texture0Sampler); break; \
    case 1: _statement(s_texture1, s_texture1Sampler); break; \
    }
#define CKFF_DISPATCH_2D_ORDINARY(_ordinal, _result, _operation) \
    CKFF_DISPATCH_HANDLE(CKFFTexture2D, CKFF_2D_SLOT_BASE, 2, 8, _ordinal, _result, _operation)
#define CKFF_DISPATCH_DEPTH_COMPARE(_ordinal, _result, _operation) \
    CKFF_DISPATCH_HANDLE(CKFFDepthTexture2D, CKFF_2D_SLOT_BASE, 0, 2, _ordinal, _result, _operation)
#elif CKFF_DEPTH_COMPARE_SAMPLER_COUNT == 3
#define CKFF_SELECT_2D(_index, _statement) \
    switch (_index) { \
    case 3: _statement(s_texture3, s_texture3Sampler); break; \
    case 4: _statement(s_texture4, s_texture4Sampler); break; \
    case 5: _statement(s_texture5, s_texture5Sampler); break; \
    case 6: _statement(s_texture6, s_texture6Sampler); break; \
    case 7: _statement(s_texture7, s_texture7Sampler); break; \
    }
#define CKFF_SELECT_DEPTH_2D(_index, _statement) \
    switch (_index) { \
    case 0: _statement(s_texture0, s_texture0Sampler); break; \
    case 1: _statement(s_texture1, s_texture1Sampler); break; \
    case 2: _statement(s_texture2, s_texture2Sampler); break; \
    }
#define CKFF_DISPATCH_2D_ORDINARY(_ordinal, _result, _operation) \
    CKFF_DISPATCH_HANDLE(CKFFTexture2D, CKFF_2D_SLOT_BASE, 3, 8, _ordinal, _result, _operation)
#define CKFF_DISPATCH_DEPTH_COMPARE(_ordinal, _result, _operation) \
    CKFF_DISPATCH_HANDLE(CKFFDepthTexture2D, CKFF_2D_SLOT_BASE, 0, 3, _ordinal, _result, _operation)
#elif CKFF_DEPTH_COMPARE_SAMPLER_COUNT == 4
#define CKFF_SELECT_2D(_index, _statement) \
    switch (_index) { \
    case 4: _statement(s_texture4, s_texture4Sampler); break; \
    case 5: _statement(s_texture5, s_texture5Sampler); break; \
    case 6: _statement(s_texture6, s_texture6Sampler); break; \
    case 7: _statement(s_texture7, s_texture7Sampler); break; \
    }
#define CKFF_SELECT_DEPTH_2D(_index, _statement) \
    switch (_index) { \
    case 0: _statement(s_texture0, s_texture0Sampler); break; \
    case 1: _statement(s_texture1, s_texture1Sampler); break; \
    case 2: _statement(s_texture2, s_texture2Sampler); break; \
    case 3: _statement(s_texture3, s_texture3Sampler); break; \
    }
#define CKFF_DISPATCH_2D_ORDINARY(_ordinal, _result, _operation) \
    CKFF_DISPATCH_HANDLE(CKFFTexture2D, CKFF_2D_SLOT_BASE, 4, 8, _ordinal, _result, _operation)
#define CKFF_DISPATCH_DEPTH_COMPARE(_ordinal, _result, _operation) \
    CKFF_DISPATCH_HANDLE(CKFFDepthTexture2D, CKFF_2D_SLOT_BASE, 0, 4, _ordinal, _result, _operation)
#elif CKFF_DEPTH_COMPARE_SAMPLER_COUNT == 5
#define CKFF_SELECT_2D(_index, _statement) \
    switch (_index) { \
    case 5: _statement(s_texture5, s_texture5Sampler); break; \
    case 6: _statement(s_texture6, s_texture6Sampler); break; \
    case 7: _statement(s_texture7, s_texture7Sampler); break; \
    }
#define CKFF_SELECT_DEPTH_2D(_index, _statement) \
    switch (_index) { \
    case 0: _statement(s_texture0, s_texture0Sampler); break; \
    case 1: _statement(s_texture1, s_texture1Sampler); break; \
    case 2: _statement(s_texture2, s_texture2Sampler); break; \
    case 3: _statement(s_texture3, s_texture3Sampler); break; \
    case 4: _statement(s_texture4, s_texture4Sampler); break; \
    }
#define CKFF_DISPATCH_2D_ORDINARY(_ordinal, _result, _operation) \
    CKFF_DISPATCH_HANDLE(CKFFTexture2D, CKFF_2D_SLOT_BASE, 5, 8, _ordinal, _result, _operation)
#define CKFF_DISPATCH_DEPTH_COMPARE(_ordinal, _result, _operation) \
    CKFF_DISPATCH_HANDLE(CKFFDepthTexture2D, CKFF_2D_SLOT_BASE, 0, 5, _ordinal, _result, _operation)
#elif CKFF_DEPTH_COMPARE_SAMPLER_COUNT == 6
#define CKFF_SELECT_2D(_index, _statement) \
    switch (_index) { \
    case 6: _statement(s_texture6, s_texture6Sampler); break; \
    case 7: _statement(s_texture7, s_texture7Sampler); break; \
    }
#define CKFF_SELECT_DEPTH_2D(_index, _statement) \
    switch (_index) { \
    case 0: _statement(s_texture0, s_texture0Sampler); break; \
    case 1: _statement(s_texture1, s_texture1Sampler); break; \
    case 2: _statement(s_texture2, s_texture2Sampler); break; \
    case 3: _statement(s_texture3, s_texture3Sampler); break; \
    case 4: _statement(s_texture4, s_texture4Sampler); break; \
    case 5: _statement(s_texture5, s_texture5Sampler); break; \
    }
#define CKFF_DISPATCH_2D_ORDINARY(_ordinal, _result, _operation) \
    CKFF_DISPATCH_HANDLE(CKFFTexture2D, CKFF_2D_SLOT_BASE, 6, 8, _ordinal, _result, _operation)
#define CKFF_DISPATCH_DEPTH_COMPARE(_ordinal, _result, _operation) \
    CKFF_DISPATCH_HANDLE(CKFFDepthTexture2D, CKFF_2D_SLOT_BASE, 0, 6, _ordinal, _result, _operation)
#elif CKFF_DEPTH_COMPARE_SAMPLER_COUNT == 7
#define CKFF_SELECT_2D(_index, _statement) \
    switch (_index) { \
    case 7: _statement(s_texture7, s_texture7Sampler); break; \
    }
#define CKFF_SELECT_DEPTH_2D(_index, _statement) \
    switch (_index) { \
    case 0: _statement(s_texture0, s_texture0Sampler); break; \
    case 1: _statement(s_texture1, s_texture1Sampler); break; \
    case 2: _statement(s_texture2, s_texture2Sampler); break; \
    case 3: _statement(s_texture3, s_texture3Sampler); break; \
    case 4: _statement(s_texture4, s_texture4Sampler); break; \
    case 5: _statement(s_texture5, s_texture5Sampler); break; \
    case 6: _statement(s_texture6, s_texture6Sampler); break; \
    }
#define CKFF_DISPATCH_2D_ORDINARY(_ordinal, _result, _operation) \
    CKFF_DISPATCH_HANDLE(CKFFTexture2D, CKFF_2D_SLOT_BASE, 7, 8, _ordinal, _result, _operation)
#define CKFF_DISPATCH_DEPTH_COMPARE(_ordinal, _result, _operation) \
    CKFF_DISPATCH_HANDLE(CKFFDepthTexture2D, CKFF_2D_SLOT_BASE, 0, 7, _ordinal, _result, _operation)
#elif CKFF_DEPTH_COMPARE_SAMPLER_COUNT == 8
#define CKFF_SELECT_2D(_index, _statement)
#define CKFF_SELECT_DEPTH_2D(_index, _statement) \
    switch (_index) { \
    case 0: _statement(s_texture0, s_texture0Sampler); break; \
    case 1: _statement(s_texture1, s_texture1Sampler); break; \
    case 2: _statement(s_texture2, s_texture2Sampler); break; \
    case 3: _statement(s_texture3, s_texture3Sampler); break; \
    case 4: _statement(s_texture4, s_texture4Sampler); break; \
    case 5: _statement(s_texture5, s_texture5Sampler); break; \
    case 6: _statement(s_texture6, s_texture6Sampler); break; \
    case 7: _statement(s_texture7, s_texture7Sampler); break; \
    }
#define CKFF_DISPATCH_2D_ORDINARY(_ordinal, _result, _operation)
#define CKFF_DISPATCH_DEPTH_COMPARE(_ordinal, _result, _operation) \
    CKFF_DISPATCH_HANDLE(CKFFDepthTexture2D, CKFF_2D_SLOT_BASE, 0, 8, _ordinal, _result, _operation)
#endif
#elif CKFF_NATIVE_SAMPLER_LAYOUT == 1
#define CKFF_2D_SLOT_BASE 0
#define CKFF_CUBE_SLOT_BASE 4
#define CKFF_VOLUME_SLOT_BASE 12
#define CKFF_2D_SLOT_COUNT 4
#define CKFF_CUBE_SLOT_COUNT 8
#define CKFF_VOLUME_SLOT_COUNT 4
SAMPLER2D(s_texture0, 0);
SAMPLER2D(s_texture1, 1);
SAMPLER2D(s_texture2, 2);
SAMPLER2D(s_texture3, 3);
SAMPLERCUBE(s_textureCube0, 4);
SAMPLERCUBE(s_textureCube1, 5);
SAMPLERCUBE(s_textureCube2, 6);
SAMPLERCUBE(s_textureCube3, 7);
SAMPLERCUBE(s_textureCube4, 8);
SAMPLERCUBE(s_textureCube5, 9);
SAMPLERCUBE(s_textureCube6, 10);
SAMPLERCUBE(s_textureCube7, 11);
SAMPLER3D(s_textureVolume0, 12);
SAMPLER3D(s_textureVolume1, 13);
SAMPLER3D(s_textureVolume2, 14);
SAMPLER3D(s_textureVolume3, 15);
#define CKFF_SELECT_CUBE(_index, _statement) \
    switch (_index) { \
    case 0: _statement(s_textureCube0, s_textureCube0Sampler); break; \
    case 1: _statement(s_textureCube1, s_textureCube1Sampler); break; \
    case 2: _statement(s_textureCube2, s_textureCube2Sampler); break; \
    case 3: _statement(s_textureCube3, s_textureCube3Sampler); break; \
    case 4: _statement(s_textureCube4, s_textureCube4Sampler); break; \
    case 5: _statement(s_textureCube5, s_textureCube5Sampler); break; \
    case 6: _statement(s_textureCube6, s_textureCube6Sampler); break; \
    case 7: _statement(s_textureCube7, s_textureCube7Sampler); break; \
    }
#define CKFF_SELECT_VOLUME(_index, _statement) \
    switch (_index) { \
    case 0: _statement(s_textureVolume0, s_textureVolume0Sampler); break; \
    case 1: _statement(s_textureVolume1, s_textureVolume1Sampler); break; \
    case 2: _statement(s_textureVolume2, s_textureVolume2Sampler); break; \
    case 3: _statement(s_textureVolume3, s_textureVolume3Sampler); break; \
    }
#define CKFF_DISPATCH_CUBE(_ordinal, _result, _operation) \
    CKFF_DISPATCH_HANDLE(CKFFTextureCube, CKFF_CUBE_SLOT_BASE, 0, 8, _ordinal, _result, _operation)
#define CKFF_DISPATCH_VOLUME(_ordinal, _result, _operation) \
    CKFF_DISPATCH_HANDLE(CKFFTexture3D, CKFF_VOLUME_SLOT_BASE, 0, 4, _ordinal, _result, _operation)
#if CKFF_DEPTH_COMPARE_SAMPLER_COUNT == 0
#define CKFF_SELECT_2D(_index, _statement) \
    switch (_index) { \
    case 0: _statement(s_texture0, s_texture0Sampler); break; \
    case 1: _statement(s_texture1, s_texture1Sampler); break; \
    case 2: _statement(s_texture2, s_texture2Sampler); break; \
    case 3: _statement(s_texture3, s_texture3Sampler); break; \
    }
#define CKFF_SELECT_DEPTH_2D(_index, _statement)
#define CKFF_DISPATCH_2D_ALL(_ordinal, _result, _operation) \
    CKFF_DISPATCH_HANDLE(CKFFTexture2D, CKFF_2D_SLOT_BASE, 0, 4, _ordinal, _result, _operation)
#define CKFF_DISPATCH_2D_STAGE(_stage, _result, _operation) \
    CKFF_DISPATCH_HANDLE(CKFFTexture2D, CKFF_2D_SLOT_BASE, 0, 4, _stage, _result, _operation)
#define CKFF_DISPATCH_2D_ORDINARY(_ordinal, _result, _operation) \
    CKFF_DISPATCH_HANDLE(CKFFTexture2D, CKFF_2D_SLOT_BASE, 0, 4, _ordinal, _result, _operation)
#define CKFF_DISPATCH_DEPTH_COMPARE(_ordinal, _result, _operation)
#elif CKFF_DEPTH_COMPARE_SAMPLER_COUNT == 1
#define CKFF_SELECT_2D(_index, _statement) \
    switch (_index) { \
    case 1: _statement(s_texture1, s_texture1Sampler); break; \
    case 2: _statement(s_texture2, s_texture2Sampler); break; \
    case 3: _statement(s_texture3, s_texture3Sampler); break; \
    }
#define CKFF_SELECT_DEPTH_2D(_index, _statement) \
    switch (_index) { \
    case 0: _statement(s_texture0, s_texture0Sampler); break; \
    }
#define CKFF_DISPATCH_2D_ORDINARY(_ordinal, _result, _operation) \
    CKFF_DISPATCH_HANDLE(CKFFTexture2D, CKFF_2D_SLOT_BASE, 1, 4, _ordinal, _result, _operation)
#define CKFF_DISPATCH_DEPTH_COMPARE(_ordinal, _result, _operation) \
    CKFF_DISPATCH_HANDLE(CKFFDepthTexture2D, CKFF_2D_SLOT_BASE, 0, 1, _ordinal, _result, _operation)
#elif CKFF_DEPTH_COMPARE_SAMPLER_COUNT == 2
#define CKFF_SELECT_2D(_index, _statement) \
    switch (_index) { \
    case 2: _statement(s_texture2, s_texture2Sampler); break; \
    case 3: _statement(s_texture3, s_texture3Sampler); break; \
    }
#define CKFF_SELECT_DEPTH_2D(_index, _statement) \
    switch (_index) { \
    case 0: _statement(s_texture0, s_texture0Sampler); break; \
    case 1: _statement(s_texture1, s_texture1Sampler); break; \
    }
#define CKFF_DISPATCH_2D_ORDINARY(_ordinal, _result, _operation) \
    CKFF_DISPATCH_HANDLE(CKFFTexture2D, CKFF_2D_SLOT_BASE, 2, 4, _ordinal, _result, _operation)
#define CKFF_DISPATCH_DEPTH_COMPARE(_ordinal, _result, _operation) \
    CKFF_DISPATCH_HANDLE(CKFFDepthTexture2D, CKFF_2D_SLOT_BASE, 0, 2, _ordinal, _result, _operation)
#elif CKFF_DEPTH_COMPARE_SAMPLER_COUNT == 3
#define CKFF_SELECT_2D(_index, _statement) \
    switch (_index) { \
    case 3: _statement(s_texture3, s_texture3Sampler); break; \
    }
#define CKFF_SELECT_DEPTH_2D(_index, _statement) \
    switch (_index) { \
    case 0: _statement(s_texture0, s_texture0Sampler); break; \
    case 1: _statement(s_texture1, s_texture1Sampler); break; \
    case 2: _statement(s_texture2, s_texture2Sampler); break; \
    }
#define CKFF_DISPATCH_2D_ORDINARY(_ordinal, _result, _operation) \
    CKFF_DISPATCH_HANDLE(CKFFTexture2D, CKFF_2D_SLOT_BASE, 3, 4, _ordinal, _result, _operation)
#define CKFF_DISPATCH_DEPTH_COMPARE(_ordinal, _result, _operation) \
    CKFF_DISPATCH_HANDLE(CKFFDepthTexture2D, CKFF_2D_SLOT_BASE, 0, 3, _ordinal, _result, _operation)
#elif CKFF_DEPTH_COMPARE_SAMPLER_COUNT == 4
#define CKFF_SELECT_2D(_index, _statement)
#define CKFF_SELECT_DEPTH_2D(_index, _statement) \
    switch (_index) { \
    case 0: _statement(s_texture0, s_texture0Sampler); break; \
    case 1: _statement(s_texture1, s_texture1Sampler); break; \
    case 2: _statement(s_texture2, s_texture2Sampler); break; \
    case 3: _statement(s_texture3, s_texture3Sampler); break; \
    }
#define CKFF_DISPATCH_2D_ORDINARY(_ordinal, _result, _operation)
#define CKFF_DISPATCH_DEPTH_COMPARE(_ordinal, _result, _operation) \
    CKFF_DISPATCH_HANDLE(CKFFDepthTexture2D, CKFF_2D_SLOT_BASE, 0, 4, _ordinal, _result, _operation)
#endif
#elif CKFF_NATIVE_SAMPLER_LAYOUT == 2
#define CKFF_2D_SLOT_BASE 0
#define CKFF_CUBE_SLOT_BASE 4
#define CKFF_VOLUME_SLOT_BASE 8
#define CKFF_2D_SLOT_COUNT 4
#define CKFF_CUBE_SLOT_COUNT 4
#define CKFF_VOLUME_SLOT_COUNT 8
SAMPLER2D(s_texture0, 0);
SAMPLER2D(s_texture1, 1);
SAMPLER2D(s_texture2, 2);
SAMPLER2D(s_texture3, 3);
SAMPLERCUBE(s_textureCube0, 4);
SAMPLERCUBE(s_textureCube1, 5);
SAMPLERCUBE(s_textureCube2, 6);
SAMPLERCUBE(s_textureCube3, 7);
#if !defined(__spirv__)
Texture3D<float4> s_textureVolume[8] : register(t8, space2);
SamplerState s_textureVolumeSampler[8] : register(s8, space2);
#define CKFF_VOLUME_RESOURCE_ARRAY 1
#else
SAMPLER3D(s_textureVolume0, 8);
SAMPLER3D(s_textureVolume1, 9);
SAMPLER3D(s_textureVolume2, 10);
SAMPLER3D(s_textureVolume3, 11);
SAMPLER3D(s_textureVolume4, 12);
SAMPLER3D(s_textureVolume5, 13);
SAMPLER3D(s_textureVolume6, 14);
SAMPLER3D(s_textureVolume7, 15);
#define CKFF_VOLUME_RESOURCE_ARRAY 0
#endif
#define CKFF_SELECT_CUBE(_index, _statement) \
    switch (_index) { \
    case 0: _statement(s_textureCube0, s_textureCube0Sampler); break; \
    case 1: _statement(s_textureCube1, s_textureCube1Sampler); break; \
    case 2: _statement(s_textureCube2, s_textureCube2Sampler); break; \
    case 3: _statement(s_textureCube3, s_textureCube3Sampler); break; \
    }
#if CKFF_VOLUME_RESOURCE_ARRAY
#define CKFF_SELECT_VOLUME(_index, _statement) \
    { _statement(s_textureVolume[_index], s_textureVolumeSampler[_index]); }
#else
#define CKFF_SELECT_VOLUME(_index, _statement) \
    switch (_index) { \
    case 0: _statement(s_textureVolume0, s_textureVolume0Sampler); break; \
    case 1: _statement(s_textureVolume1, s_textureVolume1Sampler); break; \
    case 2: _statement(s_textureVolume2, s_textureVolume2Sampler); break; \
    case 3: _statement(s_textureVolume3, s_textureVolume3Sampler); break; \
    case 4: _statement(s_textureVolume4, s_textureVolume4Sampler); break; \
    case 5: _statement(s_textureVolume5, s_textureVolume5Sampler); break; \
    case 6: _statement(s_textureVolume6, s_textureVolume6Sampler); break; \
    case 7: _statement(s_textureVolume7, s_textureVolume7Sampler); break; \
    }
#endif
#define CKFF_DISPATCH_CUBE(_ordinal, _result, _operation) \
    CKFF_DISPATCH_HANDLE(CKFFTextureCube, CKFF_CUBE_SLOT_BASE, 0, 4, _ordinal, _result, _operation)
#define CKFF_DISPATCH_VOLUME(_ordinal, _result, _operation) \
    CKFF_DISPATCH_HANDLE(CKFFTexture3D, CKFF_VOLUME_SLOT_BASE, 0, 8, _ordinal, _result, _operation)
#if CKFF_DEPTH_COMPARE_SAMPLER_COUNT == 0
#define CKFF_SELECT_2D(_index, _statement) \
    switch (_index) { \
    case 0: _statement(s_texture0, s_texture0Sampler); break; \
    case 1: _statement(s_texture1, s_texture1Sampler); break; \
    case 2: _statement(s_texture2, s_texture2Sampler); break; \
    case 3: _statement(s_texture3, s_texture3Sampler); break; \
    }
#define CKFF_SELECT_DEPTH_2D(_index, _statement)
#define CKFF_DISPATCH_2D_ALL(_ordinal, _result, _operation) \
    CKFF_DISPATCH_HANDLE(CKFFTexture2D, CKFF_2D_SLOT_BASE, 0, 4, _ordinal, _result, _operation)
#define CKFF_DISPATCH_2D_STAGE(_stage, _result, _operation) \
    CKFF_DISPATCH_HANDLE(CKFFTexture2D, CKFF_2D_SLOT_BASE, 0, 4, _stage, _result, _operation)
#define CKFF_DISPATCH_2D_ORDINARY(_ordinal, _result, _operation) \
    CKFF_DISPATCH_HANDLE(CKFFTexture2D, CKFF_2D_SLOT_BASE, 0, 4, _ordinal, _result, _operation)
#define CKFF_DISPATCH_DEPTH_COMPARE(_ordinal, _result, _operation)
#elif CKFF_DEPTH_COMPARE_SAMPLER_COUNT == 1
#define CKFF_SELECT_2D(_index, _statement) \
    switch (_index) { \
    case 1: _statement(s_texture1, s_texture1Sampler); break; \
    case 2: _statement(s_texture2, s_texture2Sampler); break; \
    case 3: _statement(s_texture3, s_texture3Sampler); break; \
    }
#define CKFF_SELECT_DEPTH_2D(_index, _statement) \
    switch (_index) { \
    case 0: _statement(s_texture0, s_texture0Sampler); break; \
    }
#define CKFF_DISPATCH_2D_ORDINARY(_ordinal, _result, _operation) \
    CKFF_DISPATCH_HANDLE(CKFFTexture2D, CKFF_2D_SLOT_BASE, 1, 4, _ordinal, _result, _operation)
#define CKFF_DISPATCH_DEPTH_COMPARE(_ordinal, _result, _operation) \
    CKFF_DISPATCH_HANDLE(CKFFDepthTexture2D, CKFF_2D_SLOT_BASE, 0, 1, _ordinal, _result, _operation)
#elif CKFF_DEPTH_COMPARE_SAMPLER_COUNT == 2
#define CKFF_SELECT_2D(_index, _statement) \
    switch (_index) { \
    case 2: _statement(s_texture2, s_texture2Sampler); break; \
    case 3: _statement(s_texture3, s_texture3Sampler); break; \
    }
#define CKFF_SELECT_DEPTH_2D(_index, _statement) \
    switch (_index) { \
    case 0: _statement(s_texture0, s_texture0Sampler); break; \
    case 1: _statement(s_texture1, s_texture1Sampler); break; \
    }
#define CKFF_DISPATCH_2D_ORDINARY(_ordinal, _result, _operation) \
    CKFF_DISPATCH_HANDLE(CKFFTexture2D, CKFF_2D_SLOT_BASE, 2, 4, _ordinal, _result, _operation)
#define CKFF_DISPATCH_DEPTH_COMPARE(_ordinal, _result, _operation) \
    CKFF_DISPATCH_HANDLE(CKFFDepthTexture2D, CKFF_2D_SLOT_BASE, 0, 2, _ordinal, _result, _operation)
#elif CKFF_DEPTH_COMPARE_SAMPLER_COUNT == 3
#define CKFF_SELECT_2D(_index, _statement) \
    switch (_index) { \
    case 3: _statement(s_texture3, s_texture3Sampler); break; \
    }
#define CKFF_SELECT_DEPTH_2D(_index, _statement) \
    switch (_index) { \
    case 0: _statement(s_texture0, s_texture0Sampler); break; \
    case 1: _statement(s_texture1, s_texture1Sampler); break; \
    case 2: _statement(s_texture2, s_texture2Sampler); break; \
    }
#define CKFF_DISPATCH_2D_ORDINARY(_ordinal, _result, _operation) \
    CKFF_DISPATCH_HANDLE(CKFFTexture2D, CKFF_2D_SLOT_BASE, 3, 4, _ordinal, _result, _operation)
#define CKFF_DISPATCH_DEPTH_COMPARE(_ordinal, _result, _operation) \
    CKFF_DISPATCH_HANDLE(CKFFDepthTexture2D, CKFF_2D_SLOT_BASE, 0, 3, _ordinal, _result, _operation)
#elif CKFF_DEPTH_COMPARE_SAMPLER_COUNT == 4
#define CKFF_SELECT_2D(_index, _statement)
#define CKFF_SELECT_DEPTH_2D(_index, _statement) \
    switch (_index) { \
    case 0: _statement(s_texture0, s_texture0Sampler); break; \
    case 1: _statement(s_texture1, s_texture1Sampler); break; \
    case 2: _statement(s_texture2, s_texture2Sampler); break; \
    case 3: _statement(s_texture3, s_texture3Sampler); break; \
    }
#define CKFF_DISPATCH_2D_ORDINARY(_ordinal, _result, _operation)
#define CKFF_DISPATCH_DEPTH_COMPARE(_ordinal, _result, _operation) \
    CKFF_DISPATCH_HANDLE(CKFFDepthTexture2D, CKFF_2D_SLOT_BASE, 0, 4, _ordinal, _result, _operation)
#endif
#else
#error Unsupported CKFF_NATIVE_SAMPLER_LAYOUT
#endif
