// Auto-generated by compile_shaders.py gen-spec-layout from CKFFSpecLayout.def - DO NOT EDIT
// Requires int ckffSpecBits(int lane, int offset, int bits) to be defined before inclusion.

#define CKFF_SPEC_LANE_BITS 24
#define CKFF_SPEC_LANE_COUNT 20
#define CKFF_SPEC_VEC4_COUNT 5
#define CKFF_SPEC_STAGE_COUNT 8
#define CKFF_SPEC_STAGE_LANE_BASE 0
#define CKFF_SPEC_STAGE_LANE_STRIDE 2
#define CKFF_SPEC_GLOBAL_LANE_BASE 16

int ckffSpecStageBits(int stage, int laneInStage, int offset, int bits)
{
    return ckffSpecBits(CKFF_SPEC_STAGE_LANE_BASE + stage * CKFF_SPEC_STAGE_LANE_STRIDE + laneInStage, offset, bits);
}

int ckffSpecStage_COLOR_OP(int stage) { return ckffSpecStageBits(stage, 0, 0, 5); }
int ckffSpecStage_COLOR_ARG1(int stage) { return ckffSpecStageBits(stage, 0, 5, 5); }
int ckffSpecStage_COLOR_ARG2(int stage) { return ckffSpecStageBits(stage, 0, 10, 5); }
int ckffSpecStage_COLOR_ARG0(int stage) { return ckffSpecStageBits(stage, 0, 15, 5); }
int ckffSpecStage_RESULT_IS_TEMP(int stage) { return ckffSpecStageBits(stage, 0, 20, 1); }
int ckffSpecStage_SAMPLER_TYPE(int stage) { return ckffSpecStageBits(stage, 0, 21, 2); }
int ckffSpecStage_PROJECTED(int stage) { return ckffSpecStageBits(stage, 0, 23, 1); }
int ckffSpecStage_ALPHA_OP(int stage) { return ckffSpecStageBits(stage, 1, 0, 5); }
int ckffSpecStage_ALPHA_ARG1(int stage) { return ckffSpecStageBits(stage, 1, 5, 5); }
int ckffSpecStage_ALPHA_ARG2(int stage) { return ckffSpecStageBits(stage, 1, 10, 5); }
int ckffSpecStage_ALPHA_ARG0(int stage) { return ckffSpecStageBits(stage, 1, 15, 5); }
int ckffSpecStage_SAMPLER_COMPARE_FUNC(int stage) { return ckffSpecStageBits(stage, 1, 20, 4); }

int ckffSpec_LAST_ACTIVE_TEXTURE_STAGE() { return ckffSpecBits(16, 0, 3); }
int ckffSpec_ALPHA_TEST_ENABLED() { return ckffSpecBits(16, 3, 1); }
int ckffSpec_ALPHA_FUNC() { return ckffSpecBits(16, 4, 4); }
int ckffSpec_FOG_ENABLED() { return ckffSpecBits(16, 8, 1); }
int ckffSpec_VERTEX_FOG_MODE() { return ckffSpecBits(16, 9, 2); }
int ckffSpec_PIXEL_FOG_MODE() { return ckffSpecBits(16, 11, 2); }
int ckffSpec_RANGE_FOG() { return ckffSpecBits(16, 13, 1); }
int ckffSpec_FLAT_SHADE() { return ckffSpecBits(16, 14, 1); }
int ckffSpec_GLOBAL_SPECULAR_ENABLED() { return ckffSpecBits(16, 15, 1); }
int ckffSpec_MIRRORONCE_SAMPLER_MASK() { return ckffSpecBits(17, 0, 24); }
