"""Offline DX11 rectangle-clear shaders; no runtime compilation or bgfx patch."""
import argparse
from pathlib import Path
import subprocess
import tempfile

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--shaderc', required=True, type=Path)
parser.add_argument('--bgfx-source', required=True, type=Path)
parser.add_argument('--verify', action='store_true')
args = parser.parse_args()
source = Path(__file__).resolve().parent
with tempfile.TemporaryDirectory(prefix='ckre-clear-') as temp:
    for prefix, stage in [('vs', 'vertex'), ('fs', 'fragment')]:
        name = prefix + '_rect_clear'
        binary = Path(temp) / (name + '.bin')
        subprocess.run([str(args.shaderc.resolve()), '-f', str(source / (name + '.sc')),
            '-o', str(binary), '--type', stage, '--platform', 'windows', '-p', 's_5_0',
            '-i', str(args.bgfx_source.resolve() / 'src'), '--varyingdef', str(source / 'varying.def.sc')], check=True)
        data = binary.read_bytes()
        lines = ['// Generated by compile_clear_shaders.py; do not edit.',
                 f'static const unsigned char ck_{name}_dx11[] = {{']
        lines += ['    ' + ', '.join(f'0x{b:02x}' for b in data[i:i + 16]) + ',' for i in range(0, len(data), 16)]
        text = '\n'.join(lines + ['};', ''])
        header = source / (name + '.h')
        if args.verify:
            if header.read_text() != text:
                raise SystemExit(f'Stale generated shader: {header}')
        else:
            header.write_text(text)
