#!/usr/bin/env python3
"""Generate CKRasterizerCapsBaseline.generated.h from caps-baseline.json.

The JSON is produced by `ckre_scene_capture --caps-json` against the original
CKDX8Rasterizer.dll (spec 4.9.2). The generated header is committed next to
src/CKRasterizer/CKRasterizerLib/CKRasterizerCapsBaseline.cpp so that no JSON
parsing happens at runtime.

Usage:
    gen_caps_baseline_header.py <caps-baseline.json> <output.h>
"""

import json
import sys
from datetime import date

# Field order of Vx3DCapsDesc in VxMath/include/VxDefines.h.
CAPS3D_FIELDS = [
    "DevCaps",
    "RenderBpps",
    "ZBufferBpps",
    "StencilBpps",
    "StencilCaps",
    "MinTextureWidth",
    "MinTextureHeight",
    "MaxTextureWidth",
    "MaxTextureHeight",
    "MaxClipPlanes",
    "VertexCaps",
    "MaxActiveLights",
    "MaxNumberBlendStage",
    "MaxNumberTextureStage",
    "MaxTextureRatio",
    "TextureFilterCaps",
    "TextureAddressCaps",
    "TextureCaps",
    "MiscCaps",
    "AlphaCmpCaps",
    "ZCmpCaps",
    "RasterCaps",
    "SrcBlendCaps",
    "DestBlendCaps",
    "CKRasterizerSpecificCaps",
]

# Field order of Vx2DCapsDesc.
CAPS2D_FIELDS = [
    "Family",
    "MaxVideoMemory",
    "AvailableVideoMemory",
    "Caps",
]


def to_int(value, name):
    if isinstance(value, bool):
        raise SystemExit(f"field {name}: booleans are not allowed")
    if isinstance(value, int):
        return value
    if isinstance(value, str):
        text = value.strip()
        try:
            return int(text, 0)
        except ValueError:
            raise SystemExit(f"field {name}: cannot parse integer from {value!r}")
    raise SystemExit(f"field {name}: unsupported value {value!r}")


def read_fields(section, names, section_name):
    values = []
    missing = [n for n in names if n not in section]
    if missing:
        raise SystemExit(f"{section_name}: missing fields {missing}")
    extra = [n for n in section if n not in names]
    if extra:
        raise SystemExit(f"{section_name}: unknown fields {extra}")
    for name in names:
        v = to_int(section[name], f"{section_name}.{name}")
        if v < 0 or v > 0xFFFFFFFF:
            raise SystemExit(f"{section_name}.{name}: out of 32-bit range")
        values.append(v)
    return values


def c_string(text):
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main(argv):
    if len(argv) != 3:
        print(__doc__, file=sys.stderr)
        return 2
    src_path, out_path = argv[1], argv[2]
    with open(src_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    source = data.get("source")
    if not isinstance(source, str) or not source:
        raise SystemExit("top-level 'source' string is required")
    caps3d = read_fields(data.get("caps3D", {}), CAPS3D_FIELDS, "caps3D")
    caps2d = read_fields(data.get("caps2D", {}), CAPS2D_FIELDS, "caps2D")

    lines = []
    lines.append("// Generated by tools/gen_caps_baseline_header.py from")
    lines.append(f"// tests/reference/caps-baseline.json on {date.today().isoformat()}. Do not edit.")
    lines.append("#ifndef CKRASTERIZERCAPSBASELINE_GENERATED_H")
    lines.append("#define CKRASTERIZERCAPSBASELINE_GENERATED_H")
    lines.append("")
    lines.append(f"#define CKRST_CAPS_BASELINE_SOURCE {c_string(source)}")
    lines.append("")
    lines.append("// Vx3DCapsDesc, field order as declared in VxDefines.h")
    lines.append("#define CKRST_CAPS_BASELINE_3D_INIT { \\")
    for name, value in zip(CAPS3D_FIELDS, caps3d):
        lines.append(f"    0x{value:08X}u, /* {name} */ \\")
    lines.append("}")
    lines.append("")
    lines.append("// Vx2DCapsDesc")
    lines.append("#define CKRST_CAPS_BASELINE_2D_INIT { \\")
    lines.append(f"    (CKRST_RSTFAMILY){caps2d[0]}, /* Family */ \\")
    for name, value in zip(CAPS2D_FIELDS[1:], caps2d[1:]):
        lines.append(f"    0x{value:08X}u, /* {name} */ \\")
    lines.append("}")
    lines.append("")
    lines.append("#endif // CKRASTERIZERCAPSBASELINE_GENERATED_H")
    lines.append("")

    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    print(f"wrote {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
