##############################################################################
# CK2_3D Render Engine config file
#
# Runtime options. Defaults favor the full quality render path.
##############################################################################

<CK2_3D>
    DisablePerspectiveCorrection = 0
    ForceLinearFog = 0
    ForceSoftware = 0
    DisableFilter = 0
    EnsureVertexShader = 0
    UseIndexBuffers = 1
    DisableDithering = 0
    Antialias = 0
    DisableMipmap = 0
    DisableSpecular = 0
    EnableScreenDump = 0
    EnableDebugMode = 0
    VertexCache = 16
    SortTransparentObjects = 1
    TextureCacheManagement = 1
    TextureVideoFormat = _32_ARGB8888
    SpriteVideoFormat = _32_ARGB8888
</CK2_3D>
