#ifndef CKFFSPECIALIZATIONINFO_H
#define CKFFSPECIALIZATIONINFO_H

#include "CKRenderEngineTypes.h"

enum CKFFSpecConstantId {
    CKFF_SPEC_LAST_ACTIVE_TEXTURE_STAGE = 0,
    CKFF_SPEC_GLOBAL_SPECULAR_ENABLED,
    CKFF_SPEC_PROJECTED_SAMPLER_MASK,
    CKFF_SPEC_ALPHA_TEST_ENABLED,
    CKFF_SPEC_ALPHA_FUNC,
    CKFF_SPEC_FOG_ENABLED,
    CKFF_SPEC_VERTEX_FOG_MODE,
    CKFF_SPEC_PIXEL_FOG_MODE,
    CKFF_SPEC_RANGE_FOG,
    CKFF_SPEC_FLAT_SHADE,

    CKFF_SPEC_STAGE0_COLOR_OP,
    CKFF_SPEC_STAGE0_COLOR_ARG0,
    CKFF_SPEC_STAGE0_COLOR_ARG1,
    CKFF_SPEC_STAGE0_COLOR_ARG2,
    CKFF_SPEC_STAGE0_ALPHA_OP,
    CKFF_SPEC_STAGE0_ALPHA_ARG0,
    CKFF_SPEC_STAGE0_ALPHA_ARG1,
    CKFF_SPEC_STAGE0_ALPHA_ARG2,
    CKFF_SPEC_STAGE0_RESULT_IS_TEMP,

    CKFF_SPEC_STAGE1_COLOR_OP,
    CKFF_SPEC_STAGE1_COLOR_ARG0,
    CKFF_SPEC_STAGE1_COLOR_ARG1,
    CKFF_SPEC_STAGE1_COLOR_ARG2,
    CKFF_SPEC_STAGE1_ALPHA_OP,
    CKFF_SPEC_STAGE1_ALPHA_ARG0,
    CKFF_SPEC_STAGE1_ALPHA_ARG1,
    CKFF_SPEC_STAGE1_ALPHA_ARG2,
    CKFF_SPEC_STAGE1_RESULT_IS_TEMP,

    CKFF_SPEC_STAGE2_COLOR_OP,
    CKFF_SPEC_STAGE2_COLOR_ARG0,
    CKFF_SPEC_STAGE2_COLOR_ARG1,
    CKFF_SPEC_STAGE2_COLOR_ARG2,
    CKFF_SPEC_STAGE2_ALPHA_OP,
    CKFF_SPEC_STAGE2_ALPHA_ARG0,
    CKFF_SPEC_STAGE2_ALPHA_ARG1,
    CKFF_SPEC_STAGE2_ALPHA_ARG2,
    CKFF_SPEC_STAGE2_RESULT_IS_TEMP,

    CKFF_SPEC_STAGE3_COLOR_OP,
    CKFF_SPEC_STAGE3_COLOR_ARG0,
    CKFF_SPEC_STAGE3_COLOR_ARG1,
    CKFF_SPEC_STAGE3_COLOR_ARG2,
    CKFF_SPEC_STAGE3_ALPHA_OP,
    CKFF_SPEC_STAGE3_ALPHA_ARG0,
    CKFF_SPEC_STAGE3_ALPHA_ARG1,
    CKFF_SPEC_STAGE3_ALPHA_ARG2,
    CKFF_SPEC_STAGE3_RESULT_IS_TEMP,

    CKFF_SPEC_CONSTANT_COUNT
};

struct CKFFSpecBitfield {
    CKDWORD DwordOffset;
    CKDWORD BitOffset;
    CKDWORD BitCount;
};

class CKFFSpecializationInfo {
public:
    static const CKDWORD MaxSpecDwords = 10;

    CKFFSpecializationInfo();

    void Set(CKFFSpecConstantId id, CKDWORD value);
    CKDWORD Get(CKFFSpecConstantId id) const;
    void SetDwords(const CKDWORD *data, CKDWORD count);
    void SetOptimized(bool optimized);
    bool IsOptimized() const;

    const CKDWORD *Data() const { return m_Data; }
    CKDWORD DwordCount() const { return MaxSpecDwords; }

    static CKFFSpecBitfield Layout(CKFFSpecConstantId id);
    static CKDWORD RepackArg(CKDWORD arg);

private:
    CKDWORD m_Data[MaxSpecDwords];
};

#endif // CKFFSPECIALIZATIONINFO_H
