#ifndef CK_RENDER_CONFIG_H
#define CK_RENDER_CONFIG_H

#ifndef CKRE_ENABLE_DEBUG_LOGGER
#define CKRE_ENABLE_DEBUG_LOGGER 0
#endif

#ifndef CKRE_ENABLE_RENDER_STATS
#define CKRE_ENABLE_RENDER_STATS 0
#endif

#ifndef CKRE_ENABLE_FFP_DIAGNOSTICS
#define CKRE_ENABLE_FFP_DIAGNOSTICS 0
#endif

#ifndef CKRE_ENABLE_FRAME_DIAGNOSTICS
#define CKRE_ENABLE_FRAME_DIAGNOSTICS 0
#endif

#ifndef CKRE_ENABLE_MESH_DIAGNOSTICS
#define CKRE_ENABLE_MESH_DIAGNOSTICS 0
#endif

#endif
