foreach (_relative IN LISTS CKRE_REQUIRED_RUNTIME_FILES)
    if (NOT EXISTS "${STAGE_ROOT}/${_relative}" OR IS_DIRECTORY "${STAGE_ROOT}/${_relative}")
        message(FATAL_ERROR "[CKRenderEngine] Missing runtime file: ${STAGE_ROOT}/${_relative}")
    endif ()
endforeach ()
include("${CMAKE_CURRENT_LIST_DIR}/CKRERasterizers.cmake")
ckre_get_rasterizers(_enabled _disabled "${CKRE_STATIC_RUNTIME}")
foreach (_name IN LISTS _disabled)
    foreach (_directory IN ITEMS Bin RenderEngines)
        ckre_runtime_library_names(_filenames "${_name}")
        foreach (_filename IN LISTS _filenames)
            if (EXISTS "${STAGE_ROOT}/${_directory}/${_filename}" OR
                    IS_SYMLINK "${STAGE_ROOT}/${_directory}/${_filename}")
                message(FATAL_ERROR "[CKRenderEngine] Disabled runtime file: ${_directory}/${_filename}")
            endif ()
        endforeach ()
    endforeach ()
endforeach ()
message(STATUS "[CKRenderEngine] Runtime layout verified")
