include("${CMAKE_CURRENT_LIST_DIR}/CKREShaderc.cmake")

function(check host host_arch target target_arch cross expected)
    _ckre_can_run_tool("${host}" "${host_arch}" "${target}" "${target_arch}" "${cross}" _actual)
    if (NOT _actual STREQUAL expected)
        message(FATAL_ERROR "Tool selection ${host}/${host_arch} -> ${target}/${target_arch}: ${_actual}, expected ${expected}")
    endif ()
endfunction()

check(Windows AMD64 Windows Win32 ON ON)
check(Windows ARM64 Windows ARM64 OFF ON)
check(Windows AMD64 Windows ARM64 ON OFF)
check(Windows AMD64 Linux x86_64 ON OFF)
check(Linux x86_64 Windows x64 ON OFF)
check(Linux x86_64 Linux x86_64 OFF ON)
check(Linux x86_64 Linux aarch64 ON OFF)
check(Linux x86_64 Linux x86_64 ON OFF)
check(Darwin arm64 Darwin "x86_64;arm64" OFF ON)
check(Darwin arm64 Darwin x86_64 OFF OFF)
check(Darwin arm64 iOS arm64 ON OFF)

set(CMAKE_HOST_SYSTEM_NAME Windows)
set(CMAKE_EXECUTABLE_SUFFIX "")
_ckre_host_executable_suffix(_suffix)
if (NOT _suffix STREQUAL ".exe")
    message(FATAL_ERROR "Windows host tool lost its executable suffix")
endif ()
set(CMAKE_HOST_SYSTEM_NAME Linux)
set(CMAKE_EXECUTABLE_SUFFIX ".exe")
_ckre_host_executable_suffix(_suffix)
if (NOT _suffix STREQUAL "")
    message(FATAL_ERROR "Linux host tool inherited the target executable suffix")
endif ()

set(CMAKE_SYSTEM_NAME Darwin)
set(CMAKE_OSX_ARCHITECTURES "x86_64;arm64")
set(CMAKE_HOST_SYSTEM_PROCESSOR arm64)
_ckre_target_architecture(_architectures)
if (NOT _architectures STREQUAL "x86_64;arm64")
    message(FATAL_ERROR "Universal target slices were lost")
endif ()
