# Remove only known plugin binaries left by a previous stage configuration.
# Keep user configuration, other plugins and assets. External install prefixes
# are never cleaned automatically.
if (NOT DEFINED BUILD_ROOT OR NOT DEFINED STAGE_ROOT OR NOT DEFINED CKRE_BUILD_SDL_GPU_RASTERIZER)
    message(FATAL_ERROR "Build/stage roots and the rasterizer option are required")
endif ()
get_filename_component(_build_root "${BUILD_ROOT}" REALPATH)
get_filename_component(_stage_root "${STAGE_ROOT}" REALPATH)
include("${CMAKE_CURRENT_LIST_DIR}/CKRERasterizers.cmake")
ckre_get_rasterizers(_enabled _disabled "${CKRE_STATIC_RUNTIME}")
set(_build_compare "${_build_root}")
set(_stage_compare "${_stage_root}")
if (CMAKE_HOST_WIN32)
    string(TOLOWER "${_build_compare}" _build_compare)
    string(TOLOWER "${_stage_compare}" _stage_compare)
endif ()
string(FIND "${_stage_compare}/" "${_build_compare}/" _stage_prefix)
set(_remove "")
foreach (_name IN LISTS _disabled)
    foreach (_directory IN ITEMS Bin RenderEngines)
        ckre_runtime_library_names(_filenames "${_name}")
        foreach (_filename IN LISTS _filenames)
            set(_path "${_stage_root}/${_directory}/${_filename}")
            if (EXISTS "${_path}" OR IS_SYMLINK "${_path}")
                get_filename_component(_resolved "${_path}" REALPATH)
                if (CMAKE_HOST_WIN32)
                    string(TOLOWER "${_resolved}" _resolved)
                endif ()
                string(FIND "${_resolved}" "${_stage_compare}/" _file_prefix)
                if (NOT _stage_prefix EQUAL 0 OR _stage_compare STREQUAL _build_compare OR
                        NOT _file_prefix EQUAL 0 OR IS_DIRECTORY "${_path}")
                    message(FATAL_ERROR "Cannot automatically remove stale rasterizer outside an isolated build stage: ${_path}")
                endif ()
                list(APPEND _remove "${_path}")
            endif ()
        endforeach ()
    endforeach ()
endforeach ()
# Validate the entire set before removing any files.
foreach (_path IN LISTS _remove)
    file(REMOVE "${_path}")
    if (EXISTS "${_path}" OR IS_SYMLINK "${_path}")
        message(FATAL_ERROR "Could not remove stale rasterizer (close the Player first): ${_path}")
    endif ()
    message(STATUS "[Stage] Removed disabled rasterizer: ${_path}")
endforeach ()
