if (NOT DEFINED TEST_ROOT)
    message(FATAL_ERROR "TEST_ROOT is required")
endif ()
include("${CMAKE_CURRENT_LIST_DIR}/CKRERasterizers.cmake")
unset(CKRE_BUILD_SDL_GPU_RASTERIZER)
unset(CKRE_STATIC_RUNTIME)
ckre_get_rasterizers(_enabled _disabled "${CKRE_STATIC_RUNTIME}")
if (NOT _enabled STREQUAL "CKSdlGpuRasterizer" OR NOT _disabled STREQUAL "CKBgfxRasterizer" OR
        DEFINED CKRE_BUILD_SDL_GPU_RASTERIZER)
    message(FATAL_ERROR "Script defaults or caller option isolation changed")
endif ()
set(CKRE_BUILD_SDL_GPU_RASTERIZER ON)
set(CKRE_STATIC_RUNTIME ON)
ckre_get_rasterizers(_enabled _disabled "${CKRE_STATIC_RUNTIME}")
if (NOT _enabled STREQUAL "CKSdlGpuRasterizer" OR
        NOT _disabled STREQUAL "CKBgfxRasterizer;CKSdlGpuRasterizer")
    message(FATAL_ERROR "Static providers must remain registered without dynamic binaries")
endif ()
set(_stage "${TEST_ROOT}/build/stage")
file(MAKE_DIRECTORY "${_stage}/RenderEngines" "${_stage}/Bin")
foreach (_file IN ITEMS CKBgfxRasterizer.dll CKSdlGpuRasterizer.dll UserRasterizer.dll CKBgfxRasterizer.ini)
    file(WRITE "${_stage}/RenderEngines/${_file}" "test fixture: ${_file}")
endforeach ()
# The retired bgfx provider of an earlier stage configuration.
ckre_runtime_library_names(_platform_names CKBgfxRasterizer)
foreach (_filename IN LISTS _platform_names)
    file(WRITE "${_stage}/Bin/${_filename}" "platform fixture")
endforeach ()

function(_prune sdl static stage expect_success)
    execute_process(COMMAND "${CMAKE_COMMAND}"
        "-DBUILD_ROOT=${TEST_ROOT}/build" "-DSTAGE_ROOT=${stage}"
        "-DCKRE_BUILD_SDL_GPU_RASTERIZER=${sdl}" "-DCKRE_STATIC_RUNTIME=${static}"
        -P "${CMAKE_CURRENT_LIST_DIR}/CKREPruneRasterizers.cmake"
        RESULT_VARIABLE _result OUTPUT_VARIABLE _output ERROR_VARIABLE _error)
    if ((expect_success AND NOT _result EQUAL 0) OR (NOT expect_success AND _result EQUAL 0))
        message(FATAL_ERROR "Unexpected pruning outcome: ${_result}\n${_output}\n${_error}")
    endif ()
endfunction()

function(_verify expect_success required)
    execute_process(COMMAND "${CMAKE_COMMAND}" "-DSTAGE_ROOT=${_stage}"
        -DCKRE_BUILD_SDL_GPU_RASTERIZER=ON -DCKRE_STATIC_RUNTIME=OFF
        "-DCKRE_REQUIRED_RUNTIME_FILES=${required}"
        -P "${CMAKE_CURRENT_LIST_DIR}/CKREVerifyRuntime.cmake"
        RESULT_VARIABLE _result OUTPUT_VARIABLE _output ERROR_VARIABLE _error)
    if ((expect_success AND NOT _result EQUAL 0) OR (NOT expect_success AND _result EQUAL 0))
        message(FATAL_ERROR "Unexpected verification outcome: ${_result}\n${_output}\n${_error}")
    endif ()
endfunction()

_verify(FALSE "RenderEngines/CKSdlGpuRasterizer.dll")
_prune(ON OFF "${_stage}" TRUE)
foreach (_filename IN LISTS _platform_names)
    if (EXISTS "${_stage}/Bin/${_filename}")
        message(FATAL_ERROR "Retired platform binary was retained: ${_filename}")
    endif ()
endforeach ()
_verify(TRUE "RenderEngines/CKSdlGpuRasterizer.dll")
_verify(FALSE "RenderEngines/CK2_3D.ini")
if (EXISTS "${_stage}/RenderEngines/CKBgfxRasterizer.dll" OR
        NOT EXISTS "${_stage}/RenderEngines/CKSdlGpuRasterizer.dll")
    message(FATAL_ERROR "SDL stage contains the wrong rasterizers")
endif ()
_prune(OFF OFF "${_stage}" TRUE)
if (EXISTS "${_stage}/RenderEngines/CKSdlGpuRasterizer.dll")
    message(FATAL_ERROR "Disabled SDL_gpu rasterizer was retained")
endif ()
file(WRITE "${_stage}/RenderEngines/CKSdlGpuRasterizer.dll" "re-enabled plugin")
_prune(ON ON "${_stage}" TRUE)
if (EXISTS "${_stage}/RenderEngines/CKSdlGpuRasterizer.dll")
    message(FATAL_ERROR "Static stage retains a dynamic rasterizer")
endif ()
if (CMAKE_HOST_WIN32)
    file(WRITE "${_stage}/RenderEngines/libCKBgfxRasterizer.dll" "MinGW fixture")
    string(TOUPPER "${_stage}" _case_variant)
    _prune(ON OFF "${_case_variant}" TRUE)
    if (EXISTS "${_stage}/RenderEngines/libCKBgfxRasterizer.dll")
        message(FATAL_ERROR "Case-variant Windows prefix was not cleaned")
    endif ()
endif ()
foreach (_file IN ITEMS UserRasterizer.dll CKBgfxRasterizer.ini)
    file(READ "${_stage}/RenderEngines/${_file}" _content)
    if (NOT _content STREQUAL "test fixture: ${_file}")
        message(FATAL_ERROR "Unrelated plugin/configuration changed")
    endif ()
endforeach ()

file(MAKE_DIRECTORY "${TEST_ROOT}/external/RenderEngines")
file(WRITE "${TEST_ROOT}/external/RenderEngines/CKBgfxRasterizer.dll" "external plugin")
_prune(ON OFF "${TEST_ROOT}/external" FALSE)
file(READ "${TEST_ROOT}/external/RenderEngines/CKBgfxRasterizer.dll" _external)
if (NOT _external STREQUAL "external plugin")
    message(FATAL_ERROR "External install was changed")
endif ()
