// Generated by tools/gen_caps_baseline_header.py from
// tests/reference/caps-baseline.json on 2026-09-02. Do not edit.
#ifndef CKRASTERIZERCAPSBASELINE_GENERATED_H
#define CKRASTERIZERCAPSBASELINE_GENERATED_H

#define CKRST_CAPS_BASELINE_SOURCE "CKDX8Rasterizer.dll (Ballance retail, RenderEngines/CK2_3D.dll 2002-10-30) | NVIDIA GeForce RTX 4090 (T&L DX8) | Windows 11 x64, 32-bit process | captured 2026-09-02 by ckre_scene_capture --caps-json"

// Vx3DCapsDesc, field order as declared in VxDefines.h
#define CKRST_CAPS_BASELINE_3D_INIT { \
    0x001BBEF0u, /* DevCaps */ \
    0x00000000u, /* RenderBpps */ \
    0x00000000u, /* ZBufferBpps */ \
    0x00000000u, /* StencilBpps */ \
    0x000000FFu, /* StencilCaps */ \
    0x00000001u, /* MinTextureWidth */ \
    0x00000001u, /* MinTextureHeight */ \
    0x00004000u, /* MaxTextureWidth */ \
    0x00004000u, /* MaxTextureHeight */ \
    0x00000008u, /* MaxClipPlanes */ \
    0x0000003Bu, /* VertexCaps */ \
    0x00000008u, /* MaxActiveLights */ \
    0x00000008u, /* MaxNumberBlendStage */ \
    0x00000008u, /* MaxNumberTextureStage */ \
    0x00004000u, /* MaxTextureRatio */ \
    0x0303073Fu, /* TextureFilterCaps */ \
    0x0000003Fu, /* TextureAddressCaps */ \
    0x0001ECC5u, /* TextureCaps */ \
    0x00000EF2u, /* MiscCaps */ \
    0x000000FFu, /* AlphaCmpCaps */ \
    0x000000FFu, /* ZCmpCaps */ \
    0x00F37191u, /* RasterCaps */ \
    0x00001FFFu, /* SrcBlendCaps */ \
    0x00001FFFu, /* DestBlendCaps */ \
    0x000104CDu, /* CKRasterizerSpecificCaps */ \
}

// Vx2DCapsDesc
#define CKRST_CAPS_BASELINE_2D_INIT { \
    (CKRST_RSTFAMILY)0, /* Family */ \
    0x00000000u, /* MaxVideoMemory */ \
    0x00000000u, /* AvailableVideoMemory */ \
    0x00000007u, /* Caps */ \
}

#endif // CKRASTERIZERCAPSBASELINE_GENERATED_H
